\chapterfont{\color{white}}

# Vectors

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[RoyalPurple,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[RoyalPurple,very thick] (5,1) -- (6,1);
\draw[RoyalPurple,fill=RoyalPurple,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Vectors}}};
\node at (3,1) {\Large{\textsc{Chapter 8}}};
\end{tikzpicture}
\end{center}

## Parallel Vectors

\newpage

### Exercise {-}

\newpage

## Collinearity using Vectors

\newpage

### Exercise {-}

\newpage

## The Division of a Line in a Ratio

\newpage

### Exercise {-}

\newpage

## Unit Vectors $i$, $j$ and $k$

\newpage

### Exercise {-}

\newpage

## The Scalar Product

\newpage

### Exercise {-}

\newpage

## The Angle Between Two Vectors

\newpage

### Exercise {-}

\newpage

## Properties of the Scalar Product

\newpage

### Exercise {-}

\newpage

## Vector Pathways

\newpage

### Exercise {-}

\newpage

## Review Exercise {-}
