\chapterfont{\color{white}}

# Polynomials

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[PineGreen,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[PineGreen,very thick] (5,1) -- (6,1);
\draw[PineGreen,fill=PineGreen,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Polynomials}}};
\node at (3,1) {\Large{\textsc{Chapter 10}}};
\end{tikzpicture}
\end{center}


## Polynomials and Synthetic Division

\vspace{-0.5cm}

Expressions comprised of sums of \textit{positive, integer} powers of $x$ are referred to as \textit{polynomials in }$x$.

\begin{multicols}{5}
    \begin{center}
        \begin{tikzpicture}
            \draw[white] (-1.5,-1.7) rectangle (1.5,1.7);
            \node at (0,2.5) {\textbf{Constant}};
            \node at (0,2) {\textcolor{PineGreen}{\textit{Degree 0}}};
            \node at (0,1.5) {e.g. $7$};
            \draw[domain=-1.3:1.3,smooth] plot (\x,0);
        \end{tikzpicture}
    \end{center}
    \begin{center}
        \begin{tikzpicture}
            \draw[white] (-1.5,-1.7) rectangle (1.5,1.7);
            \node at (0,2.5) {\textbf{Linear}};
            \node at (0,2) {\textcolor{PineGreen}{\textit{Degree 1}}};
            \node at (0,1.5) {e.g. $2x+4$};
            \draw[domain=-1.3:1.3,smooth] plot (\x,0.5*\x);
        \end{tikzpicture}
    \end{center}
    \begin{center}
        \begin{tikzpicture}
            \draw[white] (-1.5,-1.7) rectangle (1.5,1.7);
            \node at (0,2.5) {\textbf{Quadratic}};
            \node at (0,2) {\textcolor{PineGreen}{\textit{Degree 2}}};
            \node at (0,1.5) {e.g. $x^2-3x+1$};
            \draw[domain=-1.4:1.4,smooth] plot (\x,0.5*\x*\x-0.5);
        \end{tikzpicture}
    \end{center}
    \begin{center}
        \begin{tikzpicture}
            \draw[white] (-1.5,-1.7) rectangle (1.5,1.7);
            \node at (0,2.5) {\textbf{Cubic}};
            \node at (0,2) {\textcolor{PineGreen}{\textit{Degree 3}}};
            \node at (0,1.5) {e.g. $4x^3-2x$};
            \draw[domain=-1.1:1.6,smooth] plot (\x,\x*\x*\x-\x*\x-\x+0.5);
        \end{tikzpicture}
    \end{center}
    \begin{center}
        \begin{tikzpicture}
            \draw[white] (-1.5,-1.7) rectangle (1.5,1.7);
            \node at (0,2.5) {\textbf{Quartic}};
            \node at (0,2) {\textcolor{PineGreen}{\textit{Degree 4}}};
            \node at (0,1.5) {e.g. $x^4-3x^3+1$};
            \draw[domain=-1.1:1.4,smooth] plot (\x,\x*\x*\x*\x-\x*\x*\x-\x*\x+\x);
        \end{tikzpicture}
    \end{center}
\end{multicols}

\vspace{-1.3cm}

A polynomial function such as $f(x)=2x^3-7x^2+4x-1$ can be evaluated for some value of $x$:

\vspace{-0.6cm}

\begin{align*}
    f(3)&=2(3)^3-7(3)^2+4(3)+1\\
    &=54-63+12+1\\
    &=4
\end{align*}

\vspace{-0.4cm}

Another way to evaluate $f(3)$ is to use synthetic division, as follows:

1) Draw a table as below and fill in the first row, then bring the first coefficient down:

\vspace{-0.2cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-2,1.6) -- (14,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (0.75,1.2) {$2$};
        \node at (2.25,1.2) {$-7$};
        \node at (3.75,1.2) {$4$};
        \node at (5.25,1.2) {$1$};
        \node at (-0.75,1.2) {$3$};
        \node at (0.75,-0.4) {$2$};
        \draw[stealth-,PineGreen] (6.5,1.2) -- (7.5,1.2) node[right] {\text{Coefficients of }$2x^3-7x^2+4x+1$};
        \draw[stealth-,PineGreen] (-0.9,0.9) -- (-1.5,0) node[below] {$x=3$};
        \draw[-stealth,PineGreen] (0.75,0.8) -- (0.75,0.2);
    \end{tikzpicture}
\end{center}

\vspace{-0.2cm}

2) The 6 is obtained by \textit{multiplying} 2 by 3, and the -1 by \textit{adding} the two values above:

\vspace{-0.2cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-2,1.6) -- (14,1.6);
        \draw[PineGreen!10,fill=PineGreen!10] (1.9,-0.7) rectangle (2.6,1.5);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (0.75,1.2) {$2$};
        \node at (2.25,1.2) {$-7$};
        \node at (3.75,1.2) {$4$};
        \node at (5.25,1.2) {$1$};
        \node at (-0.75,1.2) {$3$};
        \node at (0.75,-0.4) {$2$};
        \node at (2.25,0.4) {$\phantom{-}6$};
        \node at (2.25,-0.4) {$-1$};
        \node[right,PineGreen] at (7.5,1.2) {\textit{Multiply diagonally by 3}};
        \node[right,PineGreen] at (7.5,0.4) {\textit{Add columns}};
        \draw[PineGreen] (-0.75,1.2) circle (0.3cm);
        \draw[-stealth,PineGreen] (1.1,-0.2) -- (1.7,0.2);
    \end{tikzpicture}
\end{center}

\vspace{-0.2cm}

3) By continuing this \textit{multiplying then adding} pattern, the value of $f(3)=4$ can be obtained:

\vspace{-0.2cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-2,1.6) -- (14,1.6);
        \draw[PineGreen!10,fill=PineGreen!10] (4.5,-0.8) rectangle (6,0);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (0.75,1.2) {$2$};
        \node at (2.25,1.2) {$-7$};
        \node at (3.75,1.2) {$\phantom{-}4$};
        \node at (5.25,1.2) {$1$};
        \node at (-0.75,1.2) {$3$};
        \node at (0.75,-0.4) {$2$};
        \node at (2.25,0.4) {$\phantom{-}6$};
        \node at (2.25,-0.4) {$-1$};
        \node at (3.75,0.4) {$-3$};
        \node at (3.75,-0.4) {$\phantom{-}1$};
        \node at (5.25,0.4) {$3$};
        \node at (5.25,-0.4) {$4$};
        \draw[stealth-,PineGreen] (6.5,-0.4) -- (7.5,-0.4) node[right] {$\therefore f(3)=4$};
    \end{tikzpicture}
\end{center}

\begin{tcolorbox}[title=Example 10.1.1,colback=PineGreen!2, colframe=PineGreen]

Given $f(x)=x^4-4x^3+3x^2+9$, use synthetic division to evaluate $f(2)$.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (-1.5,1.6) -- (-1.5,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-2.25,1.2) {$2$};
        \node at (-0.75,1.2) {$1$};
        \node at (0.75,1.2) {$-4$};
        \node at (2.25,1.2) {$\phantom{-}3$};
        \node at (3.75,1.2) {$\phantom{-}0$};
        \node at (5.25,1.2) {$\phantom{-}9$};
        \node at (-0.75,-0.4) {$1$};
        \node at (0.75,0.4) {$\phantom{-}2$};
        \node at (0.75,-0.4) {$-2$};
        \node at (2.25,0.4) {$-4$};
        \node at (2.25,-0.4) {$-1$};
        \node at (3.75,0.4) {$-2$};
        \node at (3.75,-0.4) {$-2$};
        \node at (5.25,0.4) {$-4$};
        \node at (5.25,-0.4) {$\phantom{-}5$};
        \node[right] at (6.5,-0.4) {$\therefore f(2)=5$};
    \end{tikzpicture}
\end{center}

\end{tcolorbox}

The top line within a synthetic division box should be \textit{ordered in decreasing powers of }$x$.\\Any missing powers are included with a coefficient of \textit{zero}.

\pagebreak

## Remainder Theorem

\vspace{-0.5cm}

Addition, subtraction and multiplication of polynomials were all required for the National 5 course.

Since $3\times 4 + 1=13$, this implies that:

$$\dfrac{13}{3}=4\textbf{ Remainder }1$$

Since $(x-2)(x^2-3x+4)+7=x^3-5x^2+x-1$, this implies that:

$$\dfrac{x^3-5x^2+x-1}{x-2}=x^2-3x+4\textbf{ Remainder }7$$

Note that for $f(x)=x^3-5x^2+x-1$, $f(2)=(2)^3-5(2)^2+(2)-1=7$.

\begin{center}
\begin{tcolorbox}[colback=red!5,width=18cm,colframe=red!70!black]
\textbf{Remainder Theorem:}\\
    \begin{center}
        If polynomial $f(x)$ is divided by a linear divisor $(x-a)$ then the remainder is $f(a)$, and\\[0.4em] $f(x)=(x-a)Q(x)+f(a)$ where quotient $Q(x)$ is a polynomial of degree one less than $f(x)$.
    \end{center}
\end{tcolorbox}
\end{center}

\begin{tcolorbox}[title=Example 10.2.1,colback=PineGreen!2, colframe=PineGreen]

Find the remainder when $3x^3-x^2+5$ is divided by $(x-1)$.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$1$};
        \node at (0.75,1.2) {$3$};
        \node at (2.25,1.2) {$-1$};
        \node at (3.75,1.2) {$0$};
        \node at (5.25,1.2) {$5$};
        \node at (0.75,-0.4) {$3$};
        \node at (2.25,0.4) {$\phantom{-}3$};
        \node at (2.25,-0.4) {$\phantom{-}2$};
        \node at (3.75,0.4) {$2$};
        \node at (3.75,-0.4) {$2$};
        \node at (5.25,0.4) {$2$};
        \node at (5.25,-0.4) {$7$};
        \node[right,PineGreen] at (6.5,-0.4) {$\longleftarrow$ \textit{Remainder}};
        \node[left,PineGreen] at (-2.5,1.2) {$(x-1)$};
        \node[left,PineGreen] at (-2.5,0.4) {$\rightarrow f(1)$};
    \end{tikzpicture}
\end{center}

So the remainder is $7$.

\end{tcolorbox}

The \textit{quotient}, $Q(x)$, can be determined from the values to the left of the remainder.\\ Since  $3x^3-x^2+5$ is a \textit{cubic}, the quotient $Q(x)$ is \textit{quadratic}:\quad $3x^2+2x+2$.

$$3x^3-x^2+5=(x-1)(3x^2+2x+2)+7$$

\begin{tcolorbox}[title=Example 10.2.2,colback=PineGreen!2, colframe=PineGreen]

Function $f$ is defined by $f(x)=x^3+4x^2-3x-7$. Find the remainder $r$ when $f(x)$ is divided by $(x+1)$, and hence express $f(x)$ in the form $(x+1)Q(x)+r$ where $Q(x)$ is a quadratic.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$-1$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$\phantom{-}4$};
        \node at (3.75,1.2) {$-3$};
        \node at (5.25,1.2) {$-7$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$-1$};
        \node at (2.25,-0.4) {$\phantom{-}3$};
        \node at (3.75,0.4) {$-3$};
        \node at (3.75,-0.4) {$-6$};
        \node at (5.25,0.4) {$\phantom{-}6$};
        \node at (5.25,-0.4) {$-1$};
        \node[right,PineGreen] at (6.5,-0.4) {$\longleftarrow$ \textit{Remainder}};
        \node[left,PineGreen] at (-0.5,-0.4) {\textit{Quotient}$\longrightarrow$};
    \end{tikzpicture}
\end{center}

So the remainder is $-1$ and $x^3+4x^2-3x-7=(x+1)(x^2+3x-6)-1$.

\end{tcolorbox}

\pagebreak

\section*{10.3 Factor Theorem}

\vspace{-0.5cm}

Since 20 can be divided by 5 to give 4 \textbf{with no remainder}, this means 5 is a \textbf{factor} of 20.

\vspace{-0.2cm}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=18cm,colframe=red!70!black]
\textbf{Factor Theorem:}\\[-0.5em]
    \begin{center}
        If polynomial $f(x)$ is divided by a linear \textbf{factor} $(x-a)$ then the \textbf{remainder }${f(a)=0}$, and\\[0.4em] $f(x)=(x-a)Q(x)$ where quotient $Q(x)$ is a polynomial of degree one less than $f(x)$. Or:
    $$f(a)=0\iff (x-a)\text{ is a factor of }f(x)$$
    \end{center}
\end{tcolorbox}
\end{center}

\vspace{-0.3cm}

Given a linear factor, synthetic division allows a cubic expression $f(x)$ to be expressed as a the product of the \textit{linear} factor and a \textit{quadratic} quotient, which may potentially by further factorised:
\vspace{-0.1cm}
\begin{align*}
    f(x)=&\text{ }(\textit{cubic})\\
    \qquad \qquad \qquad \qquad =&\text{ }(\textit{linear})(\textit{quadratic})&&\textcolor{PineGreen}{\longleftarrow\textit{ Using synthetic division}}\\
    =&\text{ }(\textit{linear})(\textit{linear})(\textit{linear})
\end{align*}

\vspace{-0.3cm}

\begin{tcolorbox}[title=Example 10.3.1,colback=PineGreen!2, colframe=PineGreen]

Show that $(x+4)$ is a factor of $x^3-x^2-14x+24$, and hence factorise it fully.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$-4$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$-1$};
        \node at (3.75,1.2) {$-14$};
        \node at (5.25,1.2) {$\phantom{-}24$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$-4$};
        \node at (2.25,-0.4) {$-5$};
        \node at (3.75,0.4) {$\phantom{-}20$};
        \node at (3.75,-0.4) {$\phantom{-}6$};
        \node at (5.25,0.4) {$-24$};
        \node at (5.25,-0.4) {$\phantom{-}0$};
        \node[right,PineGreen] at (6.5,-0.4) {$\longleftarrow$ \textit{Remainder}};
        \node[left,PineGreen] at (-0.5,-0.4) {\textit{Quotient}$\longrightarrow$};
    \end{tikzpicture}
\end{center}
\centering
Remainder$=0\therefore (x+4)$ is a factor. \textcolor{PineGreen}{$\longleftarrow$ \textit{``Show that..''}}

\vspace{-0.3cm}
\begin{align*}
    &\text{ }x^3-x^2-14x+24\\
    =&\text{ }(x+4)(x^2-5x+6)\\
    =&\text{ }(x+4)(x-2)(x-3)
\end{align*}

\end{tcolorbox}

For some cubic expressions, a resulting quadratic quotient may not be able to be factorised.

\begin{tcolorbox}[title=Example 10.3.2,colback=PineGreen!2, colframe=PineGreen]

Show that $(x-2)$ is a factor of $2x^3-x^2+x-14$, and hence factorise it fully.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$2$};
        \node at (0.75,1.2) {$2$};
        \node at (2.25,1.2) {$-1$};
        \node at (3.75,1.2) {$1$};
        \node at (5.25,1.2) {$-14$};
        \node at (0.75,-0.4) {$2$};
        \node at (2.25,0.4) {$\phantom{-}4$};
        \node at (2.25,-0.4) {$\phantom{-}3$};
        \node at (3.75,0.4) {$6$};
        \node at (3.75,-0.4) {$7$};
        \node at (5.25,0.4) {$\phantom{-}14$};
        \node at (5.25,-0.4) {$\phantom{-}0$};
    \end{tikzpicture}
\end{center}
\centering
\textcolor{PineGreen}{\textit{``Show that }$(x-2)$\textit{ is a factor...'' }$\longrightarrow$} Remainder$=0\therefore (x-2)$ is a factor.

\vspace{-0.3cm}
\begin{align*}
    &\text{ }2x^3-x^2+x-14\\
    =&\text{ }(x-2)(2x^2+3x+7)
\end{align*}

Since $3^2-4\times2\times7=-65$, and $-65<0$, the quadratic quotient cannot be factorised\\ Therefore the cubic cannot be further factorised. 

\end{tcolorbox}

\pagebreak

Where a linear factor of a polynomial function is unknown, a suggested approach is to consider the factors of the constant term with the aim of obtaining a value such that the remainder is zero.

\begin{tcolorbox}[title=Example 10.3.3,colback=PineGreen!2, colframe=PineGreen]

Factorise $x^3-x^2-17x=15$.

\tcblower

\textcolor{PineGreen}{\textit{Consider }$\pm1,\pm3\pm5\pm15$}\\[-0.5em]

$f(1)=(1)^3-(1)^2-17(1)-15=-32\therefore$ $(x-1)$ is \textbf{not} a factor.\\[-0.5em]

$f(-1)=(-1)^3-(-1)^2-17(-1)-15=0\therefore$ $(x+1)$ \textbf{is} a factor.


\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$-1$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$-1$};
        \node at (3.75,1.2) {$-17$};
        \node at (5.25,1.2) {$-15$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$-1$};
        \node at (2.25,-0.4) {$-2$};
        \node at (3.75,0.4) {$\phantom{-}2$};
        \node at (3.75,-0.4) {$-15$};
        \node at (5.25,0.4) {$\phantom{-}15$};
        \node at (5.25,-0.4) {$\phantom{-}0$};
    \end{tikzpicture}
\end{center}
\centering

\vspace{-0.7cm}
\begin{align*}
    &\text{ }x^3-x^2-17x-15\\
    =&\text{ }(x+1)(x^2-2x-15)\\
    =&\text{ }(x+1)(x+3)(x-5)
\end{align*}

\end{tcolorbox}

Repeated use of synthetic dvision may allow a \textit{quartic} ($x^4$) to be expressed as a product of up to four linear factors.

\vspace{-1cm}

\begin{align*}
    f(x)=&\text{ }(\textit{quartic})\\
    =&\text{ }(\textit{linear})(\textit{cubic})&&\textcolor{PineGreen}{\longleftarrow\textit{ Using synthetic division}}\\
    \qquad \qquad \qquad =&\text{ }(\textit{linear})(\textit{linear})(\textit{quadratic})&&\textcolor{PineGreen}{\longleftarrow\textit{ Using synthetic division}}\\
    =&\text{ }(\textit{linear})(\textit{linear})(\textit{linear})(\textit{linear})
\end{align*}

\vspace{-0.1cm}

\begin{tcolorbox}[title=Example 10.3.4,colback=PineGreen!2, colframe=PineGreen]

Show that $(x-2)$ is a factor of $x^4-2x^3-7x^2+8x+12$ and hence factorise it fully.

\tcblower

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (-1.5,1.6) -- (-1.5,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-2.25,1.2) {$2$};
        \node at (-0.75,1.2) {$1$};
        \node at (0.75,1.2) {$-2$};
        \node at (2.25,1.2) {$-7$};
        \node at (3.75,1.2) {$\phantom{-}8$};
        \node at (5.25,1.2) {$\phantom{-}12$};
        \node at (-0.75,-0.4) {$1$};
        \node at (0.75,0.4) {$\phantom{-}2$};
        \node at (0.75,-0.4) {$\phantom{-}0$};
        \node at (2.25,0.4) {$\phantom{-}0$};
        \node at (2.25,-0.4) {$-7$};
        \node at (3.75,0.4) {$-14$};
        \node at (3.75,-0.4) {$-6$};
        \node at (5.25,0.4) {$-12$};
        \node at (5.25,-0.4) {$\phantom{-}0$};
    \end{tikzpicture}
\end{center}

\centering
Remainder$=0\therefore (x-2)$ is a factor.\\[0.5em]

$x^4-2x^3-7x^2+8x+12=(x-2)(x^3-7x-6)$

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-5,1.6) -- (11,1.6);
        \draw (0,1.6) -- (0,0) -- (6,0);
        \draw (4.5,0) -- (4.5,-0.8) -- (6,-0.8);
        \node at (-0.75,1.2) {$3$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$0$};
        \node at (3.75,1.2) {$-7$};
        \node at (5.25,1.2) {$-6$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$3$};
        \node at (2.25,-0.4) {$3$};
        \node at (3.75,0.4) {$\phantom{-}9$};
        \node at (3.75,-0.4) {$\phantom{-}2$};
        \node at (5.25,0.4) {$\phantom{-}6$};
        \node at (5.25,-0.4) {$\phantom{-}0$};
        \node[left] at (-1.5,0) {\textcolor{PineGreen}{\textit{Try factors of 6}}};
        \draw[PineGreen,-stealth] (-1.5,0.3) -- (-0.9,0.9);
    \end{tikzpicture}
\end{center}

\vspace{-0.8cm}

\begin{align*}
    x^4-2x^3-7x^2+8x+12&=(x-2)(x^3-7x-6)\\
    &=(x-2)(x-3)(x^2+3x+2)\\
    &=(x-2)(x-3)(x+1)(x+2)
\end{align*}

\end{tcolorbox}

\pagebreak 

## Finding Unknown Coefficients

\vspace{-0.5cm}

An unknown coefficient of a polynomial expression may be calculated if a factor of the expression is known, or the remainder given a linear divisor is known. It may be preferred to use synthetic division, or to evaluate the expression directly.

\begin{tcolorbox}[title=Example 10.4.1,colback=PineGreen!2, colframe=PineGreen]

Given that $(x+2)$ is a factor of $2x^3+kx^2-14x+8$, determine the value of $k$.

\tcblower


\begin{center}
    \begin{tikzpicture}
        \draw[white] (-4,1.6) -- (12,1.6);
        \fill[PineGreen!10] (5.5,-0.8) rectangle (7.5,0);
        \draw (0,1.6) -- (0,0) -- (7.5,0);
        \draw (5.5,0) -- (5.5,-0.8) -- (7.5,-0.8);
        \node at (-0.75,1.2) {$-2$};
        \node at (0.75,1.2) {$2$};
        \node at (2.25,1.2) {$\phantom{-}k$};
        \node at (4.25,1.2) {$-14$};
        \node at (6.55,1.2) {$8$};
        \node at (0.75,-0.4) {$2$};
        \node at (2.25,0.4) {$-4$};
        \node at (2.25,-0.4) {$k-4$};
        \node at (4.25,0.4) {$-2k+8$};
        \node at (4.25,-0.4) {$-2k-6$};
        \node at (6.55,0.4) {$4k+12$};
        \node at (6.55,-0.4) {$4k+20$};
        \node[right] at (7.7,-0.4) {\textcolor{PineGreen}{$\longleftarrow$\textit{ Remainder}}};
    \end{tikzpicture}
\end{center}
\centering
Since $(x+2)$ is a factor, remainder$=0$.
\begin{align*}
    4k+20&=0\\
    4k&=-20\\
    k&=-5
\end{align*}
\end{tcolorbox}

Where a polynomial has \textit{two} unknown coefficients, \textit{simultaneous equations} may be formed and solved.

\begin{tcolorbox}[title=Example 10.4.2,colback=PineGreen!2, colframe=PineGreen]

Find the values of $a$ and $b$ given that:\\
\begin{itemize}
    \item $(x-2)$ is a factor of $x^3+ax^2+bx+12$.
    \item $x^3+ax^2+bx+12$ divided by $(x-1)$ has a remainder of 10.
\end{itemize}

\tcblower


\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3.5,1.6) -- (11.5,1.6);
        \draw (0,1.6) -- (0,0) -- (8.9,0);
        \draw (6.1,0) -- (6.1,-0.8) -- (8.9,-0.8);
        \node at (-0.75,1.2) {$2$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$a$};
        \node at (4.55,1.2) {$b$};
        \node at (7.55,1.2) {$12$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$2$};
        \node at (2.25,-0.4) {$a+2$};
        \node at (4.55,0.4) {$2a+4$};
        \node at (4.55,-0.4) {$2a+b+4$};
        \node at (7.55,0.4) {$4a+2b+8$};
        \node at (7.55,-0.4) {$4a+2b+20$};
    \end{tikzpicture}
\end{center}
\centering
Since $(x-2)$ is a factor, remainder $=0$ $\implies$ $4a+2b+20=0$.

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3.5,1.6) -- (11.5,1.6);
        \draw (0,1.6) -- (0,0) -- (8.9,0);
        \draw (6.1,0) -- (6.1,-0.8) -- (8.9,-0.8);
        \node at (-0.75,1.2) {$1$};
        \node at (0.75,1.2) {$1$};
        \node at (2.25,1.2) {$a$};
        \node at (4.55,1.2) {$b$};
        \node at (7.55,1.2) {$12$};
        \node at (0.75,-0.4) {$1$};
        \node at (2.25,0.4) {$1$};
        \node at (2.25,-0.4) {$a+1$};
        \node at (4.55,0.4) {$a+1$};
        \node at (4.55,-0.4) {$a+b+1$};
        \node at (7.55,0.4) {$a+b+1$};
        \node at (7.55,-0.4) {$a+b+13$};
    \end{tikzpicture}
\end{center}

\centering
Remainder $=10$ $\implies$ $a+b+13=10$.
\vspace{-0.3cm}
\flushleft
\textcolor{PineGreen}{\textit{Solve simultaneously:}}
\vspace{-0.8cm}
\begin{center}
    \begin{tikzpicture}
        \node[below left] at (0,0) {
        \begin{minipage}{7cm}
            \begin{align*}
                4a+2b&=-20&\qquad \qquad 4a+2b&=-20\\[0.2em]
                a+b&=-3&\qquad \qquad 2a+2b&=-6\\[0.2em]
                &&2a&=-14\\
                &&a&=-7
            \end{align*}
        \end{minipage}
        };
        \node[below right] at (1.5,-0.57) {
        \begin{minipage}{4cm}
            \centering
            \textcolor{PineGreen}{\textit{Sub }$a=-7$:}
            \vspace{-0.3cm}
            \begin{align*}
                a+b&=-3\\[0.2em]
                (-7)+b&=-3\\[0.2em]
                b&=4
            \end{align*}
        \end{minipage}
        };
        \draw[PineGreen] (-3,-2) -- (0,-2) node[right] {\scriptsize{$(-)$}};
        \draw [decoration={brace,amplitude=0.5em},decorate,thick,PineGreen]
(-4.5,-0.8) -- (-4.5,-1.8);
        \node[PineGreen] at (-4.2,-1.8) {\scriptsize{$\times 2$}};
    \end{tikzpicture}
\end{center}
\end{tcolorbox}

\pagebreak

## Solving Polynomial Equations

\vspace{-0.5cm}

\textit{Quadratic} equations such as $x^2-4x-21=0$ are typically solved through factorising, or using the quadratic formula. There is no equivalent \textit{general formula} for solving polynomial equations of degree 3 (\textit{cubic}) or higher. Instead, such polynomial equations are solved through \textit{factorising}.

\newpage

## Identifying Polynomial Functions

Given the form a polynomial function takes and its graph, showing any $x$-intercepts and at least one other coordinate, the factorised form of the polynomial may be deduced.

\begin{itemize}
    \item An $x$-intercept (or \textit{root}) when $x=a$ implies that a polynomial has a \textit{factor} of $(x-a)$.
    \item A \textit{stationary point} at an $x$-intercept is a \textit{repeated root}, and its factor will be (at least) squared.
\end{itemize}

\begin{multicols}{2}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-4,-2.5) rectangle (4,1.5);
        \draw[-stealth] (-3,0) -- (3,0) node[below] {$x$};
        \draw[smooth,domain=-2:2,yscale=0.1] plot (\x,\x*\x+4*\x);
        \draw[fill] (0,0) circle (0.05) node[below] {$a$};
        \node[PineGreen] at (0,-1) {Root when $x=a$};
        \node[PineGreen] at (0,-1.8) {Factor of $(x-a)$};
    \end{tikzpicture}
\end{center}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-4,-2.5) rectangle (4,1.5);
        \draw[-stealth] (-3,0) -- (3,0) node[below] {$x$};
        \draw[smooth,domain=-2:2,yscale=0.2] plot (\x,\x*\x);
        \draw[fill] (0,0) circle (0.05) node[below] {$a$};
        \node[PineGreen] at (0,-1) {Repeated root when $x=a$};
        \node[PineGreen] at (0,-1.8) {Factor of $(x-a)^n$};
    \end{tikzpicture}
\end{center}
    
\end{multicols}

The diagram below shows the graph of a quartic function with equation $y=k(x-a)(x-b)(x-c)^2$.

\begin{center}
    \begin{tikzpicture}
        \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
        \draw[-stealth] (0,-2) -- (0,3) node[left] {$y$};
        \draw[smooth,domain=-3:3.3,yscale=0.1] plot (\x,\x*\x*\x*\x-9*\x*\x-4*\x+12) node[above] {$y=k(x-a)(x-b)(x-c)^2$};
        \node[below left] {$0$};
        \draw[fill] (-2,0) circle (0.05) node[below] {$-2\phantom{-}$};
        \draw[fill] (1,0) circle (0.05) node[below] {$1\phantom{.}$};
        \draw[fill] (3,0) circle (0.05) node[below] {$\phantom{..}3$};
        \draw[fill] (0,1.2) circle (0.05) node[above left] {$6$};
        \draw[PineGreen,stealth-] (-2.5,-0.5) -- (-3.5,-1.5) node[below left] {\textcolor{PineGreen}{\textit{Repeated root}}};
    \end{tikzpicture}
\end{center}

With roots at $x=1$ and $x=3$, and a \textit{repeated root} at $x=-2$, the quartic can be expressed as:

$$y=k(x-1)(x-3)(x+2)^2$$

The value of $k$ can only be found if a \textit{non-root} coordinate is also known. By substitution:

\begin{align*}
    y&=k(x-1)(x-3)(x+2)^2&&\\
    6&=k(0-1)(0-3)(0+2)^2&&\textcolor{PineGreen}{\textit{Substitute in }(0,6)}\\
    6&=k(-1)(-3)(2)^2&&\\
    6&=12k&&\\
    \frac{6}{12}&=k\\
    \frac{1}{2}&=k\\
    y&=\frac{1}{2}(x-1)(x-3)(x+2)^2&&\textcolor{PineGreen}{\textit{State equation}}
\end{align*}

By comparing the form given and the final equation, it can be seen that: $k=\frac{1}{2},a=1,b=3,c=-2$

\pagebreak

## Review Exercise {-}
