\chapterfont{\color{white}}

# Compound Angles

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[DarkOrchid,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[DarkOrchid,very thick] (5,1) -- (6,1);
\draw[DarkOrchid,fill=DarkOrchid,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Compound Angles}}};
\node at (3,1) {\Large{\textsc{Chapter 12}}};
\end{tikzpicture}
\end{center}


## The Addition Formulae

\vspace{-0.5cm}

It should be noted that $\sin{(A+B)}\ne \sin{A}+\sin{B}$:

\vspace{-0.3cm}

\begin{align*}
    &\sin{(60\degree+30\degree)}=\sin{90\degree}=1\\[0.5em]
    \textbf{but }&\sin{60\degree}+\sin{30\degree}=\frac{\sqrt{3}}{2}+\frac{1}{2}=\frac{\sqrt{3}+1}{2}
\end{align*}

\vspace{-0.3cm}

Instead, the following expansions are provided in the formula sheet, known as the \textbf{addition formulae}:

\vspace{-0.3cm}

\begin{center}
\begin{tcolorbox}[colback=red!5,colframe=red!70!black]
\centering
\textbf{Addition Formulae} \textit{(as provided on the formula sheet)}:
\begin{align*}
    \sin{(A\pm B)}&=\sin{A}\cos{B}\pm\cos{A}\sin{B}\\[1em]
    \cos{(A\pm B)}&=\cos{A}\cos{B}\mp\sin{A}\sin{B}
\end{align*}

\end{tcolorbox}
\end{center}

\vspace{-0.3cm}

They can be expanded into four formulae, covering addition and subtraction for each of $\sin$ and $\cos$:

\vspace{-0.5cm}

\begin{multicols}{2}

\begin{align*}
    \sin{(A+B)}&=\sin{A}\cos{B}+\cos{A}\sin{B}\\[0.5em]
    \sin{(A-B)}&=\sin{A}\cos{B}-\cos{A}\sin{B}
\end{align*}

\begin{align*}
    \cos{(A+B)}&=\cos{A}\cos{B}-\sin{A}\sin{B}\\[0.5em]
    \cos{(A-B)}&=\cos{A}\cos{B}+\sin{A}\sin{B}
\end{align*}

\end{multicols}

\vspace{-0.3cm}

They can be used to expand the usage of known \textit{exact values} (0\degree,30\degree,45\degree,60\degree,90\degree,180\degree,270\degree,360\degree).

\begin{tcolorbox}[title=Example 12.1.1,colback=DarkOrchid!1, colframe=DarkOrchid]

Evaluate $\sin{105}$.

\tcblower

\vspace{-0.3cm}

\begin{align*}
   \sin{105\degree}=\;&\sin{(60\degree+45\degree)}&&\color{DarkOrchid}\longleftarrow \text{Relate to known exact values}\\[0.5em]
    =\;&\sin{60\degree}\cos{45\degree}+\cos{60\degree}\sin{45\degree}&&\color{DarkOrchid}\longleftarrow \text{Expand using formula}\\[0.5em]
    =\;&\frac{\sqrt{3}}{2}\times\frac{1}{\sqrt{2}}+\frac{1}{2}\times\frac{1}{\sqrt{2}}&&\color{DarkOrchid}\longleftarrow \text{Substitute exact values}\\[0.5em]
    =\;&\frac{\sqrt{3}}{2\sqrt{2}}+\frac{1}{2\sqrt{2}}&&\\[0.5em]
    =\;&\frac{\sqrt{3}+1}{2\sqrt{2}}&&\color{DarkOrchid}\longleftarrow \text{Simplify}
\end{align*}

\end{tcolorbox}

\begin{tcolorbox}[title=Example 12.1.2,colback=DarkOrchid!1, colframe=DarkOrchid]

Evaluate $\sin{40\degree}\cos{10}-\cos{40\degree}\sin{10\degree}$.

\tcblower

\vspace{-0.3cm}

\begin{align*}
    \sin{40\degree}\cos{10}-\cos{40\degree}\sin{10\degree}=\;&\sin{(40\degree-10\degree)}&&\color{DarkOrchid}\longleftarrow \text{Recognise expanded form of }\sin{(A-B)}\\[0.5em]
    =\;&\sin{30\degree}&&\\[0.5em]
    =\;&\frac{1}{2}&&\color{DarkOrchid}\longleftarrow \text{State exact value}
\end{align*}

\end{tcolorbox}

\pagebreak

## Applications to Right-Angled Triangles

\vspace{-0.5cm}

Given a right-angled triangle containing an angle $x$, values of $\sin{x}$, $\cos{x}$ and $\tan{x}$ can be stated using \textbf{SOHCATOA}. For example with Pythagoras' Theorem used to find a missing side length if needed.

\begin{center}
    \begin{tikzpicture}
        \draw (0,0) -- (5,0) -- (5,3) -- cycle;
        \draw (4.6,0) rectangle (5,0.4);
        \node[below] at (2.5,0) {$5$ cm};
        \node[right] at (5,1.5) {$3$ cm};
        \node at (1,0.3) {$x$};
        \draw (0.7,0) arc (0:31:0.7);
        \node[left] at (2.7,1.8) {\color{DarkOrchid}By Pythagoras: $\sqrt{5^2+3^2}=$\color{black}$\sqrt{34}$};
        \node at (10,1.5) {
        \begin{minipage}{5cm}
            \begin{align*}
                \sin{x}&=\frac{\text{opp}}{\text{hyp}}=\frac{3}{\sqrt{34}}\\[1em]
                \cos{x}&=\frac{\text{adj}}{\text{hyp}}=\frac{5}{\sqrt{34}}\\[1em]
                \tan{x}&=\frac{\text{opp}}{\text{adj}}=\frac{3}{5}
            \end{align*}
        \end{minipage}
        };
    \end{tikzpicture}
\end{center}

These skills are often required in combination with applications of the addition formulae.

\begin{tcolorbox}[title=Example 12.2.1,colback=DarkOrchid!1, colframe=DarkOrchid]

The diagram below shows angles $p$ and $q$ contained within right-angled. Find $\sin{(p+q)}$.

\begin{center}
    \begin{tikzpicture}
        \draw (0,0) -- (6,0) -- (0,2) -- cycle;
        \draw (0,0) -- (-4,2) -- (0,2) -- cycle;
        \draw (-3.3,2) arc (0:-26.6:0.7);
        \draw (5.3,0) arc (180:161.6:0.7);
        \node at (-3,1.75) {$p$};
        \node at (4.7,0.2) {$q$};
        \draw (0,0) rectangle (0.3,0.3);
        \draw (0,2) rectangle (-0.3,1.7);
        \node[below] at (3,0) {$6$ cm};
        \node[above] at (-2,2) {$4$ cm};
        \node[below left] at (-1.8,1.2) {$\sqrt{20}$ cm};
    \end{tikzpicture}
\end{center}

\tcblower

\vspace{-0.3cm}

\begin{align*}
    \text{Opposite side for }p&=2&&\color{DarkOrchid}\longleftarrow \text{By Pythagoras: }\sqrt{\sqrt{20}^2-4^2}=\sqrt{20-16}=\sqrt{4}=2\\[0.5em]
    \text{Hypotenuse for }q&=\sqrt{40}&&\color{DarkOrchid}\longleftarrow \text{By Pythagoras: }\sqrt{6^2+2^2}=\sqrt{36+4}=\sqrt{40}\\[0.5em]
\end{align*}

\centering
\textcolor{DarkOrchid}{Once all side length have been calculated, values of $\sin{p},\cos{p},\sin{q},\cos{q}$ can be obtained.}

\begin{align*}
    \sin{(p+q)}&=\sin{p}\cos{q}+\cos{p}\sin{q}&&\color{DarkOrchid}\longleftarrow \text{Expand addition formula}\\[0.5em]
    &=\frac{2}{\sqrt{20}}\times\frac{6}{\sqrt{40}}+\frac{4}{\sqrt{20}}\times\frac{2}{\sqrt{40}}&&\color{DarkOrchid}\longleftarrow \text{Substitute using SOHCAHTOA}\\[0.5em]
    &=\frac{12}{\sqrt{800}}+\frac{8}{\sqrt{800}}&&\\[0.5em]
    &=\frac{20}{20\sqrt{2}}&&\\[0.5em]
    &=\frac{1}{\sqrt{2}}&&\color{DarkOrchid}\longleftarrow \text{Simplify (and rationalise if required)}\\[0.5em]
\end{align*}

\end{tcolorbox}

Other expansions such as $\cos{(p+q)}$ can be calculated similarly, and note that $\tan{(p+q)}=\dfrac{\sin{(p+q)}}{\cos{(p+q)}}$.

\pagebreak

## The Double Angle Formulae

Expansions for $\sin{2x}$ and $\cos{2x}$ in terms of $\sin{x}$ and $\cos{x}$ can be obtained from the addition formulae:

\begin{align*}
    \sin{2x}&\color{DarkOrchid}=\sin{(x+x)}&\cos{2x}&\color{DarkOrchid}=\cos{(x+x)}\\
    &\color{DarkOrchid}=\sin{x}\cos{x}+\cos{x}\sin{x}&&\color{DarkOrchid}=\cos{x}\cos{x}-\sin{x}\sin{x}\\
    &=2\sin{x}\cos{x}&&=\cos^2{x}-\sin^2{x}\\
    &&&=2\cos^2{x}-1\\
    &&&=1-2\sin^2{x}\\
\end{align*}

The other arrangements of the $\cos{2x}$ expansion come from the trigonometric identify $\sin^2{x}+\cos^2{x}=1$.
These expansions are provided in the formula sheet. Care is needed to determine \textit{whether} to expand a \textit{double angle} trig term and, in the case of $\cos{2x}$, \textit{which} expansion to use.

\begin{tcolorbox}[title=Example 12.3.1,colback=DarkOrchid!1, colframe=DarkOrchid]

The diagram below shows angle $p$ contained within a right-angled triangle. Find $\sin{(2p)}$.

\begin{center}
    \begin{tikzpicture}
        \draw (0,0) -- (6,0) -- (0,2) -- cycle;
        \draw (0,0) -- (-4,2) -- (0,2) -- cycle;
        \draw (-3.3,2) arc (0:-26.6:0.7);
        \draw (5.3,0) arc (180:161.6:0.7);
        \node at (-3,1.75) {$p$};
        \node at (4.7,0.2) {$q$};
        \draw (0,0) rectangle (0.3,0.3);
        \draw (0,2) rectangle (-0.3,1.7);
        \node[below] at (3,0) {$6$ cm};
        \node[above] at (-2,2) {$4$ cm};
        \node[below left] at (-1.8,1.2) {$\sqrt{20}$ cm};
    \end{tikzpicture}
\end{center}

\end{tcolorbox}

\begin{tcolorbox}[title=Example 12.3.2,colback=DarkOrchid!1, colframe=DarkOrchid]

Given $\sin{q}=\dfrac{4}{11}$, where $0<q<\dfrac{\pi}{2}$, find $\cos{2q}$. 

\end{tcolorbox}

## Review Exercise {-}
