\chapterfont{\color{white}}

# The Circle

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[MidnightBlue,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[MidnightBlue,very thick] (5,1) -- (6,1);
\draw[MidnightBlue,fill=MidnightBlue,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{The Circle}}};
\node at (3,1) {\Large{\textsc{Chapter 13}}};
\end{tikzpicture}
\end{center}

The circle a fundamental mathematical shape, and in this chapter its equation will be introduced.

For all points $(x,y)$ on a circle, the distance to the *centre* is the same, and that distance is the *radius*.

\begin{center}
    \begin{tikzpicture}
        \draw[thick] (0,0) circle (2cm);
        \draw[MidnightBlue,fill,thick] (0,0) circle (0.03) node[below] {$\color{black}\text{centre}$} -- (30:2) circle (0.03) node[pos=1.3] {$\color{black}(x,y)$};
        \node[MidnightBlue,rotate=30,above] at (30:1) {radius};
    \end{tikzpicture}
\end{center}

In order to fully define a circle lying on an $x$-$y$ Cartesian plane, only two properties are required:

\begin{itemize}
    \item The \textcolor{MidnightBlue}{\textbf{radius}} of the circle.
    \item The \textcolor{MidnightBlue}{\textbf{centre}} of the circle.
\end{itemize}

For any point $(x,y)$ on a circle with \textcolor{MidnightBlue}{\textbf{radius}} $\color{MidnightBlue}r$ and \textcolor{MidnightBlue}{\textbf{centre}} $\color{MidnightBlue}(a,b)$, a right-angle triangle can be constructed:

\begin{center}
    \begin{tikzpicture}[scale=1.2]
        \draw[thick] (0,0) circle (2cm);
        \draw[MidnightBlue,fill,thick] (0,0) circle (0.03) -- (30:2) circle (0.03) node[pos=1.25] {$\color{black}(x,y)$} node[pos=-0.25] {$\color{black}(a,b)$};
        \node[MidnightBlue,rotate=30,above] at (30:1) {$r$};
        \draw (30:2) -- ++(0,-1) -- (0,0);
        \draw (30:2) -- ++(0,-0.9) -- ++(-0.1,0) -- ++(0,-0.1);
        \draw[very thick,-stealth,MidnightBlue] (4,0) -- (5,0);
        \draw (7,-1) -- ++(30:4) -- ++(0,-2) -- (7,-1);
        \draw (7,-1) -- ++(30:4) -- ++(0,-1.8) -- ++(-0.2,0) -- ++(0,-0.2);
        \draw[thick,MidnightBlue] (7,-1) -- ++(30:4) node[pos=0.5,rotate=30,above] {$r$};
        \node[right] at (10.5,0) {$y-b$};
        \node[below] at (8.75,-1) {$x-a$};
    \end{tikzpicture}
\end{center}

By Pythagoras' Theorem, the set of points $(x,y)$ which lie on the circle satisfy the relationship:

\[\color{MidnightBlue}(x-a)^2+(y-b)^2=r^2\]

This is known as the \textcolor{MidnightBlue}{\textbf{equation of the circle}}.

\pagebreak

## The Equation of the Circle

\vspace{-0.5cm}

The equation of the circle, introduced on the previous page, is given in the formula list:

\vspace{-0.3cm}

\begin{center}
\begin{tcolorbox}[colback=red!5,colframe=red!70!black]
\centering
\textbf{The Equation of the Circle} \textit{(as provided on the formula sheet)}:
\begin{equation*}
    \text{The circle with centre }(a,b)\text{ and radius }r\text{ has equation: }
    (x-a)^2+(y-b)^2=r^2
\end{equation*}

\end{tcolorbox}
\end{center}

\vspace{-0.3cm}

When stating the equation of a circle, it is not necessary to expand the brackets unless specified.

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

State the equation of the circle with centre $(5,-2)$ and diameter $6\sqrt{2}$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
   &\text{centre }=(5,-2)&&\color{MidnightBlue}\longleftarrow \text{State centre }(a,b)\\[0.5em]
    &\text{radius }=3\sqrt{2}&&\color{MidnightBlue}\longleftarrow \text{State radius }r\\[0.5em]
    &\text{equation: }(x-5)^2+\left(y-(-2)\right)^2=\left(3\sqrt{2}\right)^2&&\color{MidnightBlue}\longleftarrow \text{Substitute into equation}\\[0.5em]
    &\hspace{2.5cm}(x-5)^2+(y+2)^2=18&&\color{MidnightBlue}\longleftarrow \text{Simplify}
\end{align*}

\end{tcolorbox}

The radius and centre of a circle may be quickly stated given its equation:

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue,height=3.9cm]

State the radius and centre of the circle with equation $(x+4)^2+(y-1)^2=25$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
   &\text{centre }=(-4,1)&&\color{MidnightBlue}\longleftarrow \text{State centre }(a,b)\\[0.5em]
    &\text{radius }=5&&\color{MidnightBlue}\longleftarrow \text{State radius }r\\[0.5em]
\end{align*}

\end{tcolorbox}

Knowledge from the earlier chapters such as *Straight Lines* and *Vectors* may be required, such as:

\begin{multicols}{2}

\begin{center}
\begin{tcolorbox}[colback=red!5,colframe=red!70!black,height=3.3cm]
\centering
\textbf{The Distance Formula}:
\begin{equation*}
    \text{The distance between }(x_1,y_1)\text{ and  }(x_2,y_2)\text{: }
\end{equation*}
\begin{equation*}
    \textbf{distance}=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}
\end{equation*}
\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=red!5,colframe=red!70!black,height=3.3cm]
\centering
\textbf{The Midpoint Formula}:
\begin{equation*}
    \text{The midpoint between }(x_1,y_1)\text{ and  }(x_2,y_2)\text{: }
\end{equation*}
\begin{equation*}
    \textbf{midpoint}=\left(\frac{x_1+x_2}{2},\frac{y_1+y_2}{2}\right)
\end{equation*}
\end{tcolorbox}
\end{center}

\end{multicols}

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Find the equation of the circle with line PQ as its diameter, where P$(-1,2)$ and Q$(7,-4)$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
   \text{centre }&=\left(\frac{-1+7}{2},\frac{2+(-4)}{2}\right)=(3,-1)&&\color{MidnightBlue}\longleftarrow \text{Find centre as midpoint of diameter}\\[0.5em]
    \text{radius }&=\sqrt{(3-(-1))^2+(-1-2)^2}=\sqrt{25}=5&&\color{MidnightBlue}\longleftarrow \text{Calculate radius using distance formula}\\[1em]
    &\hspace{1.5cm}(x-3)^2+(y+1)^2=25&&\color{MidnightBlue}\longleftarrow \text{Substitute into equation and simplify}
\end{align*}

\end{tcolorbox}

Note that \textcolor{MidnightBlue}{\textbf{concentric}} circles have the same centre and \textcolor{MidnightBlue}{\textbf{congruent}} circles have the same radius.

\pagebreak

### Exercise 13.1 {-}

\newpage

## The General Equation of the Circle

\vspace{-0.5cm}

The equation of the circle with centre $(3,-4)$ and radius $7$ can be expanded:

\vspace{-0.7cm}

\begin{align*}
    (x-3)^2+(y+4)^2&=49\\[0.5em]
    (x^2-6x+9)+(y^2+8y+16)&=49\\[0.5em]
    x^2+y^2-6x+8y+9+16-49&=0\\[0.5em]
    x^2+y^2-6x+8y-24&=0
\end{align*}

\vspace{-0.5cm}

This expanded form is called the \textcolor{MidnightBlue}{\textbf{general equation of the circle}}.

\vspace{-0.3cm}

\begin{center}
\begin{tcolorbox}[colback=red!5,colframe=red!70!black]
\centering
\textbf{General Equation of the Circle} \textit{(as provided on the formula sheet)}:
\begin{equation*}
    \text{The circle with centre }(-g,-f)\text{ and radius }\sqrt{g^2+f^2-c}\text{ has equation:}
\end{equation*}
\vspace{-0.6cm}
\begin{equation*}
    x^2+y^2+2gx+2fy+c=0
\end{equation*}

\end{tcolorbox}
\end{center}

\vspace{-0.3cm}

Unless specified, there is no requirement to expand the equation of the circle into the general form.

It is necessary, however, to be able to determine the radius and centre of a circle given its general equation.

By equating $x$ and $y$ coefficients, and constant terms, the radius and centre can be found:

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

A circle has equation $x^2+y^2+14x-12y+9=0$. Determine its centre and radius.

\tcblower

\vspace{-0.5cm}

\begin{align*}
    x^2+y^2+2gx+2fy+c&=0&&\color{MidnightBlue}\longleftarrow \text{Write down general equation in }g,f,c\\[0.5em]
    x^2+y^2+14x-12y+9&=0&&\color{MidnightBlue}\longleftarrow \text{Align equation of circle given}\\[1em]
    \color{MidnightBlue}g=7\hspace{0.5cm}f=-6\hspace{0.5cm}c=9&&&\color{MidnightBlue}\longleftarrow \text{Find the values of }g,f,c\\[1em]
    \text{centre}&=(-g,-f)&&\color{MidnightBlue}\longleftarrow \text{Find centre}\\[0.5em]
    &=(-7,-(-6))&&\\[0.5em]
    &=(-7,6)&&\\[1em]
    \text{radius}&=\sqrt{g^2+f^2-c}&&\color{MidnightBlue}\longleftarrow \text{Find radius}\\[0.5em]
    &=\sqrt{7^2+(-6)^2-9}&&\\[0.5em]
    &=\sqrt{49+36-9}&&\\[0.5em]
    &=\sqrt{76}&&\\[0.5em]
    &=2\sqrt{19}&&
\end{align*}

\end{tcolorbox}

Note that the equation $x^2+y^2+2gx+2fy+c=0$ only defines a circle where $g^2+f^2-c>0$.

\pagebreak

### Exercise 13.2 {-}

\newpage

## The Intersection of a Line and a Circle

\vspace{-0.5cm}

Given a circle and a line lying on the $x$-$y$ Cartesian plane, one of three possible relationships must apply:

\vspace{-0.5cm}

\begin{multicols}{3}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.7);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.7) {the line and circle intersect at two points};
        \draw[thick] (0,0) circle (1.2cm);
        \draw[thick] (-85:1.4) -- ++(60:2.4);
        \draw[MidnightBlue,fill] (0.25,-1.174) circle (0.06);
        \draw[MidnightBlue,fill] (1.14,0.37) circle (0.06);
        \node[below,MidnightBlue] at (0,-1.6) {$b^2-4ac>0$};
    \end{tikzpicture}
\end{center}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.7);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.7) {the line meets the circle at a tangent};
        \draw[thick] (0,0) circle (1.2cm);
        \draw[thick] (-30:1.2) -- ++(60:1.2) --++(-120:2.4);
        \draw[MidnightBlue,fill] (-30:1.2) circle (0.06);
        \node[below,MidnightBlue] at (0,-1.6) {$b^2-4ac=0$};
    \end{tikzpicture}
\end{center}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.7);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.7) {the line does not intersect the circle};
        \draw[thick] (0,0) circle (1.2cm);
        \draw[thick] (-60:1.6) -- ++(60:2.4);
        \node[below,MidnightBlue] at (0,-1.6) {$b^2-4ac<0$};
    \end{tikzpicture}
\end{center}

\end{multicols}

\vspace{-0.5cm}

Whether seeking to *find points of intersection*, *find the point of contact for a tangent*, or *show that the line and circle do not intersect*, the process should begin with preparing to solve simultaneous equations. 

Since the equation of a circle is difficult to write in the form "$y=\dots$", solving simultaneous equations to find points of intersection between a line and a circle will require the \textcolor{MidnightBlue}{\textbf{substitution method}}.

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Show that the line with the equation $y-x=-7$ is a tangent to the circle with the equation $x^{2}+y^{2}-4x+2y-3=0$, and find the point of contact.

\tcblower

\vspace{-0.5cm}

\begin{align*}
    y=\color{MidnightBlue}x-7&&&\color{MidnightBlue}\longleftarrow \text{Prepare the equation of the line}\\[1em]
    x^2+\color{MidnightBlue}(x-7)\color{black}^2-4x+2\color{MidnightBlue}(x-7)\color{black}-3&=0&&\color{MidnightBlue}\longleftarrow \text{Substitute into the circle's equation}\\[0.5em]
    x^2+\color{MidnightBlue}(x^2-14x+49)\color{black}-4x+2x-14-3&=0&&\color{MidnightBlue}\longleftarrow \text{Expand the brackets}\\[0.5em]
    2x^2-16x+32&=0&&\color{MidnightBlue}\longleftarrow \text{Collect like terms}\\[0.5em]
    x^2-8x+16&=0&&\color{MidnightBlue}\longleftarrow \text{Divide through by common factor of}\\[0.5em]
    (x-4)(x-4)&=0&&\color{MidnightBlue}\longleftarrow \text{Factorise}\\[1em]
    \text{repeated factor}\implies \text{tangency}&&&\color{MidnightBlue}\longleftarrow \textit{``Show that...''}\\[1em]
    x&=4&&\color{MidnightBlue}\longleftarrow \text{Solve to find }x\text{-coordinate}\\[1em]
    y&=4-7&&\color{MidnightBlue}\longleftarrow \text{Substitute to find }y\text{-coordinate}\\[0.5em]
    &=-3&&\\[0.5em]
    \text{Point of contact is }(4,-3)&&&
\end{align*}

\end{tcolorbox}

Tangency could also be shown by considering the *discriminant* ($b^2-4ac$) of the equation $x^2-8x+16=0$. However, when the point of contact is required it is quicker to use the *repeated factor* instead.

To show that a line and circle do not intersect, the disciminant must be considered, as it is not sufficient to make a conclusion based on being unable to solve through factorising.

\pagebreak

### Exercise 13.3 {-}

\newpage

## Finding the Equation of a Tangent to a Circle

\vspace{-0.5cm}

To find the equation of a tangent to any form of curve the following are generally required:

\vspace{-0.1cm}

\begin{itemize}
    \item A \textcolor{MidnightBlue}{\textbf{point}} which the tangent passes through.
    \item The \textcolor{MidnightBlue}{\textbf{gradient}} of the tangent.
\end{itemize}

\vspace{-0.1cm}

In chapter 3 (Differentiation I), the gradients of tangents to curves were found through differentiation. Since the form of the equation of the circle cannot be differentiated using methods covered in the this course, a geometric approach is used to find the tangent to a circle. 

\vspace{-0.3cm}

\begin{center}
    \begin{tikzpicture}[scale=0.9]
        \draw[thick] (0,0) circle (2.5cm);
        \draw[thick] (0,0) -- (20:2.5);
        \draw[fill] circle (0.06) node[below] {centre};
        \draw (20:2.5) --++(110:0.2) --++(-160:0.2) --++(-70:0.4) --++(20:0.2);
        \draw[thick,MidnightBlue] (20:2.5) -- ++(110:2) --++(-70:3.5) node[rotate=-70,MidnightBlue,above] {tangent} --++(-70:1.5);
        \node[rotate=20,above] at (20:1.25) {radius};
        \draw[MidnightBlue,fill] (20:2.5) circle (0.06) node[right] {point of tangency};
        \node[above,text width=9cm] at (11.5,0) {The radius and tangent are perpendicular:};
        \node[below,MidnightBlue] at (11.5,0) {$m_{\text{radius}}\times m_{\text{tangent}}=-1$};
    \end{tikzpicture}
\end{center}

\vspace{-0.4cm}

Given the point of contact (or \textit{point of tangency}) at which a tangent meets a circle, the gradient of the radius from the centre to that point should be first determined. A tangent is \textcolor{MidnightBlue}{\textbf{perpendicular to the radius}} which meets it at the point of contact.

\vspace{-0.1cm}

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Find the equation of the line which meets the circle with equation $x^{2}+y^{2}-4x+6y+3=0$ at a tangent at the point P$(5,-2)$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
    &x^2+y^2-4x+26y+3=0&&\\[0.5em]
    &\color{MidnightBlue}g\color{MidnightBlue}=-2\hspace{0.5cm}f=3\hspace{0.5cm}c=3&&\\[0.5em]
    \text{centre}&=(-g,-f)&&\\[0.5em]
    &=(2,-3)&&\color{MidnightBlue}\longleftarrow \text{Find the centre of the circle}\\[1em]
    m_{\text{radius}}&=\frac{-3-(-2)}{2-5}&&\color{MidnightBlue}\longleftarrow \text{Find the gradient of the radius}\\[0.5em]
    &=\frac{-1}{-3}&&\\[0.5em]
    &=\frac{1}{3}&&\\[0.5em]
    m_{\text{tangent}}&=-3&&\color{MidnightBlue}\longleftarrow \text{State the gradient of the tangent}\\[1em]
    y-b&=m(x-a)&&\\[0.5em]
    y-(-2)&=-3(x-5)&&\color{MidnightBlue}\longleftarrow \text{Substitude point of contact and }m_{\text{tangent}}\\[0.5em]
    y+2&=-3x+15&&\\[0.5em]
    y&=-3x+17&&
\end{align*}

\end{tcolorbox}

\vspace{-0.1cm}

\pagebreak

### Exercise 13.4 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item
\end{enumerate}

\newpage

## Points Inside and Outside Circles

\vspace{-0.5cm}

Given a circle and a point lying on the $x$-$y$ Cartesian plane, one of three possible relationships must apply, depending on the \textcolor{MidnightBlue}{\textit{distance from the centre of the circle to the point}} and the \textit{radius}:

\vspace{-0.3cm}

\begin{multicols}{3}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.5);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.5) {the point is outside the circle};
        \draw[thick] (0,0) -- (20:1.7);
        \node[rotate=20,above] at (20:0.85) {radius};
        \draw[thick] (0,0) circle (1.7cm);
        \draw[MidnightBlue,fill,thick] (0,0) circle (0.06) node[left] {C} -- (2.2,0) circle (0.06) node[right] {P};
        \node[below,MidnightBlue] at (0.85,0) {$\text{distance}$};
        \node[below,MidnightBlue] at (0,-2) {$\text{distance}>\color{black}\text{radius}$};
    \end{tikzpicture}
\end{center}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.5);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.5) {the point lies on the circle};
        \draw[thick] (0,0) -- (20:1.7);
        \node[rotate=20,above] at (20:0.85) {radius};
        \draw[thick] (0,0) circle (1.7cm);
        \draw[MidnightBlue,fill,thick] (0,0) circle (0.06) node[left] {C} -- (1.7,0) circle (0.06) node[right] {P};
        \node[below,MidnightBlue] at (0.85,0) {$\text{distance}$};
        \node[below,MidnightBlue] at (0,-2) {$\text{distance}=\color{black}\text{radius}$};
    \end{tikzpicture}
\end{center}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (-3,-2.2) rectangle (3,2.5);
        \node[below,text width=5.5cm,MidnightBlue,align=center] at (0,2.5) {the point lies outside the circle};
        \draw[thick] (0,0) -- (20:1.7);
        \node[rotate=20,above] at (20:0.85) {radius};
        \draw[thick] (0,0) circle (1.7cm);
        \draw[MidnightBlue,fill,thick] (0,0) circle (0.06) node[left] {C} -- (1.25,0) circle (0.06) node[right] {P};
        \node[below,MidnightBlue] at (0.85,0) {$\text{distance}$};
        \node[below,MidnightBlue] at (0,-2) {$\text{distance}<\color{black}\text{radius}$};
    \end{tikzpicture}
\end{center}

\end{multicols}

\vspace{-0.3cm}

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Show that the point Q$(-1,7)$ lies outside of the circle with equation $(x-3)^2+(y+5)^2=17$.

\tcblower

\vspace{-0.3cm}

\begin{align*}
    \text{centre}&=(3,-5)&&\color{MidnightBlue}\longleftarrow \text{Find the centre of the circle}\\[0.5em]
    \text{radius}&=\sqrt{17}&&\color{MidnightBlue}\longleftarrow \text{Find the radius of the circle}\\[0.5em]
    \text{distance}&=\sqrt{(-1-3)^2+(7-(-5))^2}&&\color{MidnightBlue}\longleftarrow \text{Find the distance from centre to point}\\[0.5em]
    &=\sqrt{(-4)^2+(12)^2}&&\\[0.5em]
    &=\sqrt{16+144}&&\\[0.5em]
    &=\sqrt{160}&&\\[1em]
    \text{Since }\sqrt{160}>\sqrt{17}&\text{ the point lies outside the circle}&&\color{MidnightBlue}\longleftarrow \text{State conclusion}
\end{align*}

\end{tcolorbox}

As with the equation of any curve, substituting the coordinates of a point into the equation of a circle may be used to check whether it lies on the circle or not. This can be useful when trying to determine the values of unknown constants.

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Given that the point P$(10,-3)$ lies on the circle with equation $x^2+y^2+kx+6y-11=0$, find the value of $k$.

\tcblower

\vspace{-0.3cm}

\begin{align*}
    10^2+(-3)^2+k(10)+6(-3)-11&=0&&\color{MidnightBlue}\longleftarrow \text{Substitute }(10,-3)\\[0.5em]
    100+9+10k-18-11&=0&&\color{MidnightBlue}\longleftarrow \text{Simplify}\\[0.5em]
    10k+80&=0&&\\[0.5em]
    10k&=-80&&\\[0.5em]
    k&=-8&&\color{MidnightBlue}\longleftarrow \text{Solve for }k
\end{align*}

\end{tcolorbox}

\pagebreak

### Exercise 13.5 {-}

\begin{enumerate}
    \item
\end{enumerate}

\newpage

## The Intersections of Circles

\vspace{-0.5cm}

Given two circles with \textcolor{MidnightBlue}{\textit{distance between the their centres}} $\color{MidnightBlue}\text{d}$ and \textit{radii} $\text{r}_1$ and $\text{r}_2$ (where $\text{r}_1\geqslant \text{r}_2$), one of five possible relationships must exist between the circles:

\vspace{-0.8cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white,very thin] (-4,-1.21) rectangle (15,1.21);
        \node[right,MidnightBlue] at (8,0) {the circles do not intersect};
        \node[right] at (3,0) {$\text{r}_1+\text{r}_2<\color{MidnightBlue}\text{d}$};
        \draw[thick] (-1.3,0) circle (1.2cm);
        \draw[thick] (1.3,0) circle (1cm);
        \draw[thick,fill,MidnightBlue] (-1.2,0) circle (0.06) -- (1.2,0) circle (0.06);
        \node[MidnightBlue,above] at (0.1,0) {d};
        \draw[thick] (-1.3,0) -- ++(-20:1.2);
        \draw[thick] (1.3,0) -- ++(160:1);
        \node[rotate=-20,xshift=-1.3cm,below,yshift=-0.4cm] at (-20:0.6) {$\text{r}_1$};
        \node[rotate=-20,xshift=1.3cm,above,yshift=0.4cm] at (160:0.5) {$\text{r}_2$};
    \end{tikzpicture}
\end{center}

\vspace{-1.5cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white,very thin] (-4,-1.21) rectangle (15,1.21);
        \node[right,MidnightBlue] at (8,0) {the circles touch externally};
        \node[right] at (3,0) {$\text{r}_1+\text{r}_2=\color{MidnightBlue}\text{d}$};
        \draw[thick] (-1.3,0) circle (1.2cm);
        \draw[thick] (0.9,0) circle (1cm);
        \draw[thick,fill,MidnightBlue] (-1.2,0) circle (0.06) -- (0.9,0) circle (0.06);
        \node[MidnightBlue,above] at (0.1,0) {d};
    \end{tikzpicture}
\end{center}

\vspace{-1.5cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white,very thin] (-4,-1.21) rectangle (15,1.21);
        \node[right,MidnightBlue] at (8,0) {the circles intersect at two points};
        \node[right] at (3,0) {$\text{r}_1+\text{r}_2>\color{MidnightBlue}\text{d}\color{black}>\text{r}_1-\text{r}_2$};
        \draw[thick] (-1.3,0) circle (1.2cm);
        \draw[thick] (0.3,0) circle (1cm);
        \draw[thick,fill,MidnightBlue] (-1.3,0) circle (0.06) -- (0.3,0) circle (0.06);
        \node[MidnightBlue,above] at (-0.35,0) {d};
    \end{tikzpicture}
\end{center}

\vspace{-1.5cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white,very thin] (-4,-1.21) rectangle (15,1.21);
        \node[right,MidnightBlue] at (8,0) {the circles touch internally};
        \node[right] at (3,0) {$\text{r}_1=\text{r}_2+\color{MidnightBlue}\text{d}$};
        \draw[thick] (-1.3,0) circle (1.2cm);
        \draw[thick] (-1.1,0) circle (1cm);
        \draw[thick,fill,MidnightBlue] (-1.3,0) circle (0.06) -- (-1.1,0) circle (0.06);
        \node[MidnightBlue,above] at (-1.2,0) {d};
    \end{tikzpicture}
\end{center}

\vspace{-1.5cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white,very thin] (-4,-1.21) rectangle (15,1.21);
        \node[right,MidnightBlue] at (8,0) {the circles do not intersect};
        \node[right] at (3,0) {$\text{r}_1>\text{r}_2+\color{MidnightBlue}\text{d}$};
        \draw[thick] (-1.3,0) circle (1.2cm);
        \draw[thick] (-1.2,0) circle (1cm);
        \draw[thick,fill,MidnightBlue] (-1.3,0) circle (0.06) -- (-1.2,0) circle (0.06);
        \node[MidnightBlue,above] at (-1.25,0) {d};
    \end{tikzpicture}
\end{center}

\begin{tcolorbox}[title=Example,colback=MidnightBlue!1, colframe=MidnightBlue]

Show that circles $\text{C}_1$ and $\text{C}_2$, with equations $(x-3)^2+(y+6)^2=18$ and $(x-2)^2+(y-1)^2=8$ respectively, touch externally.

\tcblower

\vspace{-0.5cm}

\begin{align*}
    \text{r}_1&=\sqrt{18}=3\sqrt{2}&&\color{MidnightBlue}\longleftarrow \text{State the radius of circle }\text{C}_1\\[0.5em]
    \text{r}_2&=\sqrt{8}=2\sqrt{2}&&\color{MidnightBlue}\longleftarrow \text{State the radius of circle }\text{C}_2\\[0.5em]
    \text{centre}_1&=(3,-6)&&\color{MidnightBlue}\longleftarrow \text{State the centre of circle }\text{C}_1\\[0.5em]
    \text{centre}_2&=(2,1)&&\color{MidnightBlue}\longleftarrow \text{State the centre of circle }\text{C}_2\\[0.5em]
    \text{distance}&=\sqrt{(3-2)^2+(-6-1)^2}&&\color{MidnightBlue}\longleftarrow \text{Find distance between centres}\\[0.5em]
    &=\sqrt{1+49}&&\\[0.5em]
    &=\sqrt{50}&&\\[1em]
    &=5\sqrt{2}&&\\[1em]
    \text{Since }3\sqrt{2}+2\sqrt{2}&=5\sqrt{2}\text{ the circles touch externally}&&\color{MidnightBlue}\longleftarrow \text{State conclusion}
\end{align*}

\vspace{-0.5cm}

\end{tcolorbox}


\newpage

### Exercise {-}

\newpage

## Review Exercise {-}




