\chapterfont{\color{white}}

# Logs and Exponentials

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[PineGreen,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[PineGreen,very thick] (5,1) -- (6,1);
\draw[PineGreen,fill=PineGreen,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Logs and Exponentials}}};
\node at (3,1) {\Large{\textsc{Chapter 15}}};
\end{tikzpicture}
\end{center}

Each part of an operation of the form $a^n$ can be described using the following terminology:

\begin{center}
    \begin{tikzpicture}
        \node at (0,0) {\large{$a^n$}};
        \draw[stealth-,PineGreen,thick] (0.3,0.2) --++(1,0.5) node[right] {"power" or "exponent" or "index"};
        \draw[stealth-,PineGreen,thick] (-0.32,0) --++(-1,0.2) node[left] {"base"};
    \end{tikzpicture}
\end{center}

*Power functions* take the form $f(x)=x^n$, with $x$ as the \textcolor{PineGreen}{\textit{base}} and a constant power, $n$.

\[\text{e.g.}\quad f(x)=x^3\]

*Exponential functions* take the form $f(x)=a^x$, with $x$ as the \textcolor{PineGreen}{\textit{exponent}} and a constant base, $a>0,a\ne 1$.

\[\text{e.g.}\quad f(x)=3^x\]

An example of an exponential function in everyday life is that of something *appreciating* by a percentage of its value, such as an antique vase of value £4000 increasing by 20\% each year. Its value after $0$ years, $1$ years, $2$ years, and so on, can be calculated as follows:

\begin{align*}
    \color{black!25}4000\times 1.2^0\;=\;&4000 && \color{PineGreen}\longleftarrow\text{After 0 years}\\[0.5em]
    4000\times 1.2^{\color{PineGreen}1}\color{black}\;=\;&4800 && \color{PineGreen}\longleftarrow\text{After 1 year}\\[0.5em]
    4000\times 1.2^{\color{PineGreen}2}\color{black}\;=\;&5760 && \color{PineGreen}\longleftarrow\text{After 2 years}\\[0.5em]
    4000\times 1.2^{\color{PineGreen}3}\color{black}\;=\;&6912 && \color{PineGreen}\longleftarrow\text{After 3 years}\\[0.5em]
    4000\times 1.2^{\color{PineGreen}4}\color{black}\;=\;&8294.40 && \color{PineGreen}\longleftarrow\text{After 4 years}
\end{align*}

The function to describe its value $V$ after $\color{PineGreen}x$ years is given by: $V(\color{PineGreen}x\color{black})=4000\times1.2^{\color{PineGreen}x}$

One advantage of defining this function is the ability to calculate the value at times other that after whole years. For example, the value after \textcolor{PineGreen}{three and a half years} can be calculated as:

\[V(\color{PineGreen}3.5\color{black})=4000\times1.2^{\color{PineGreen}3.5}=7571.72\]

This chapter will introduce a range of skills required when working with exponential functions.

\pagebreak

## Graphs of Exponential Functions

\vspace{-0.5cm}

\setlength{\columnsep}{30pt}

\begin{multicols}{2}

Where $a>1$:

\vspace{-0.2cm}

$y=a^x$ is \textit{strictly increasing} on $x\in\mathbb{R}$:

\vspace{-0.5cm}
\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw[-stealth] (-5,0) -- (5,0) node[below] {$x$};
        \draw[-stealth] (0,-1) -- (0,4.5) node[left] {$y$};
        \node[below left] {O};
        \draw[smooth,thick,PineGreen,domain=-5:5] plot (\x,{1.3^(\x)}) node[above left] {$y=a^x$};
        \draw[PineGreen,fill=PineGreen] (0,1) circle (0.05) node[above left] {$1$};
        \draw[PineGreen,fill=PineGreen] (1,1.3) circle (0.05) node[above] {$(1,a)$};
    \end{tikzpicture}
\end{center}

\vspace{-0.5cm}
This describes \textbf{exponential growth}.

\columnbreak

Where $0<a<1$:

\vspace{-0.2cm}

$y=a^x$ is \textit{strictly decreasing} on $x\in\mathbb{R}$:

\vspace{-0.5cm}
\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw[-stealth] (-5,0) -- (5,0) node[below] {$x$};
        \draw[-stealth] (0,-1) -- (0,4.5) node[left] {$y$};
        \node[below left] {O};
        \draw[smooth,thick,PineGreen,domain=-5:5] plot (\x,{0.76923^(\x)}) node[above] {$y=a^x$};
        \draw[PineGreen,fill=PineGreen] (0,1) circle (0.05) node[above left] {$1$};
        \draw[PineGreen,fill=PineGreen] (1,0.76923) circle (0.05) node[above] {$(1,a)$};
    \end{tikzpicture}
\end{center}

\vspace{-0.5cm}
This describes \textbf{exponential decay}.

\end{multicols}

\vspace{-0.5cm}

\setlength{\columnsep}{10pt}

Since $a^0=1$, any graph of the form $y=a^x$ will pass through the point $(0,1)$ for all $a\ne 0$.

Since $a^1=a$, any graph of the form $y=a^x$ will pass through the point $(1,a)$ for all $a$.

The graph of $y=a^x$ has the $x$-axis as a *horizontal asymptote* - a line that it approaches but never meets.

Determining the equation of the graph of an exponential function can typically be achieved using substitution or consideration of graph transformations, along with knowledge of points $(0,1)$ and $(1,a)$.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

The graph of $y=a^x+b$ is below. Find the values of $a$ and $b$, and state the range of $f(x)=a^x+b$.

\vspace{-0.5cm}
\begin{center}
    \begin{tikzpicture}[scale=0.9]
        \draw[-stealth] (-5,0) -- (5,0) node[below] {$x$};
        \draw[-stealth] (0,-0.3) -- (0,4) node[left] {$y$};
        \node[below left,xshift=0.2,yshift=0.2] {\small{O}};
        \draw[smooth,thick,domain=-3:4,yscale=0.2] plot (\x,{2^(\x)+1}) node[above] {$y=a^x+b$};
        \draw[fill] (0,0.4) circle (0.05) node[above left] {$2$};
        \draw[fill] (2,1) circle (0.05) node[above left] {$(2,5)$};
        \draw[dashed] (-4,0.17) -- (4,0.17);
    \end{tikzpicture}
\end{center}

\vspace{-0.4cm}

\tcblower

\vspace{-0.6cm}
\begin{align*}
    2&=a^0+b && \color{PineGreen}\longleftarrow\text{Substitute }(0,2)\\[0.5em]
    2&=1+b &&\\[0.5em]
    1&=b && \color{PineGreen}\longleftarrow\text{Solve to obtain }b\\[1em]
    5&=a^2+1 && \color{PineGreen}\longleftarrow\text{Substitute }(2,5)\text{ and }b=1\\[0.5em]
    4&=a^2 &&\\[0.5em]
    2&=a && \color{PineGreen}\longleftarrow\text{Solve to obtain }a\\[1em]
    y&=2^x+1&&\color{PineGreen}\longleftarrow\text{State equation}\\[0.5em]
    f(x)&\geqslant 1&&\color{PineGreen}\longleftarrow\text{State range}
\end{align*}

\end{tcolorbox}

\pagebreak

### Exercise 15.1 {-}

\vspace{-0.5cm}

\begin{enumerate}
    \item Find the equation of each exponential graph using the form given, then determine the value of $k$.
    \begin{enumerate}
    \vspace{-0.2cm}
        \begin{multicols}{2}
            \item[(a)] $y=a^x$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2:2] plot (\x,{0.4*3^(\x)});
            \draw[fill] (0,0.4) circle (0.07) node[above left] {$1$};
            \draw[fill] (1,1.2) circle (0.07) node[right,xshift=0.1cm] {$(1,3)$};
            \draw[fill,PineGreen] (2,3.6) circle (0.07) node[below right,xshift=-0.1cm,yshift=0.1cm] {$(2,k)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(c)] $y=a^x$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2.5:3.3,] plot (\x,{0.4*4^(0.5*\x)});
            \draw[fill] (0,0.4) circle (0.07) node[above left] {$1$};
            \draw[fill] (2,1.6) circle (0.07) node[below right] {$(2,4)$};
            \draw[fill,PineGreen] (3,3.2) circle (0.07) node[below right] {$(3,k)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(e)] $y=a^x+2$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-3:2.5,yscale=0.5] plot (\x,{2^(\x)+2});
            \draw[fill] (0,1.5) circle (0.07) node[above left] {$3$};
            \draw[dashed,thin,PineGreen] (-4,1) -- (2.5,1) node[right] {$y=k$};
            \draw[fill] (2,3) circle (0.07) node[below right] {$(2,6)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(g)] $y=a^x+b$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.5) -- (0,3.7) node[left] {$y$};
            \draw[smooth,thick,domain=-3:1.3] plot (\x,{3^(\x)-1});
            \draw[fill] (0,0) circle (0.07);
            \draw[fill] (1,2) circle (0.07) node[below right] {$(1,2)$};
            \node[above left] {\scriptsize{O}};
            \draw[dashed,thin] (-4,-1) -- (2.5,-1) node[right] {$y=-1$};
            \draw[fill,PineGreen] (0.5,0.732) circle (0.07) node[below right] {$(0.5,k)$};
            \end{tikzpicture}
            \item[(b)] $y=a^x$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-3.5:3.5] plot (\x,{0.75^(\x)});
            \draw[fill,PineGreen] (0,1) circle (0.07) node[below left] {$k$};
            \draw[fill] (2.40942,0.5) circle (0.07) node[above right] {$(1,0.5)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(d)] $y=4^x+b$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.5) -- (0,3.7) node[left] {$y$};
            \draw[smooth,thick,domain=-2.8:2.1,yscale=0.2] plot (\x,{4^(\x)-5});
            \draw[fill] (2,2.2) circle (0.07) node[right] {$(2,11)$};
            \draw[dashed,thin,PineGreen] (-4,-1.1) -- (2.5,-1.1) node[right] {$y=k$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(f)] $y=a^x+b$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-3.5:2.5] plot (\x,{1.5^(\x)+1});
            \draw[fill] (0,2) circle (0.07) node[above left] {$2$};
            \draw[fill] (1,2.5) circle (0.07) node[below right] {$(1,2.5)$};
            \draw[dashed,thin] (-4,1) -- (4,1);
            \draw[fill,PineGreen] (2,3.25) circle (0.07) node[below right] {$(2,k)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \item[(h)] $y=a^x+b$\\
            \begin{tikzpicture}[scale=0.8]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-2) -- (0,3.2) node[left] {$y$};
            \draw[smooth,thick,domain=-3:1.4] plot (\x,{3^(\x)-2});
            \draw[fill] (0,-1) circle (0.07) node[left] {$-1$};
            \draw[fill] (1,1) circle (0.07) node[right] {$(1,1)$};
            \draw[dashed,thin] (-4,-2) -- (4,-2);
            \draw[fill,PineGreen] (-1,-1.666666666) circle (0.07) node[above left] {$(-1,k)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{multicols}
    \end{enumerate}
    \vspace{-0.5cm}
    \item Sketch the graph of each of the following, and state the range of $y=f(x)$:
    \vspace{-0.3cm}
    \begin{enumerate}
        \begin{multicols}{4}
            \item $y=3^x$
            \item $y=3^x+1$
            \item $y=3^x-2$
            \item $y=3^{x+2}$
        \end{multicols}
        \begin{multicols}{4}
            \item $y=0.5^x$
            \item $y=0.5^x-1$
            \item $y=0.5^{x-3}$
            \item $y=0.5^{1-x}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Evaluating Logarithms

\vspace{-0.5cm}

The function $f(x)=\color{PineGreen}\log_a{\color{black}x}$, where $a>0$ and $x>0$, is defined as the inverse function to $f(x)=\color{PineGreen}a^{\color{black}x}$.

\begin{center}
\begin{tcolorbox}[colback=red!5,width=10cm,colframe=red!70!black,height=2.2cm]
\vspace{-0.5cm}

\begin{align*}
    \text{If }\hspace{1.9cm} x&=a^y\\[0.5em]
    \text{ then }\hspace{0.5cm} \log_a{x}&=y \qquad (\text{where }a>0,x>0)
\end{align*}

\end{tcolorbox}
\end{center}

\vspace{-0.2cm}

A numerical example will help build an understanding of how to interpret a logarithm:

\vspace{-0.8cm}

\begin{align*}
    \text{Since }\hspace{1.2cm} 8&=\color{PineGreen}2^{\color{black}3}\\[0.5em]
    \text{ then }\hspace{0.5cm}\color{PineGreen}\log_2\color{black}{8}&=3
\end{align*}

\vspace{-0.3cm}

Hence $\log_2{8}$ ("log to the base 2 of 8") can be read as: "2 raised to *which power* gives a value of 8?"

\begin{multicols}{2}

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,width=8.5cm,height=2.8cm]

Evaluate $\log_3{81}$.

\vspace{-0.1cm}
\tcblower

$\log_3{81}=4\color{PineGreen}\longleftarrow\text{Since }3^4=81$

\end{tcolorbox}



\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,width=8.5cm,height=2.8cm]

Evaluate $\log_7{49}$.

\vspace{-0.1cm}
\tcblower

$\log_7{49}=2\color{PineGreen}\longleftarrow\text{Since }7^2=49$

\end{tcolorbox}

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,width=8.5cm,height=2.8cm]

Evaluate $\log_5{1}$.

\vspace{-0.1cm}
\tcblower

$\log_5{1}=0\color{PineGreen}\longleftarrow\text{Since }5^0=1$

\end{tcolorbox}

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,width=8.5cm,height=2.8cm]

Evaluate $\log_3{\frac{1}{9}}$.

\vspace{-0.1cm}
\tcblower

$\log_3{\frac{1}{9}}=-2\color{PineGreen}\longleftarrow\text{Since }3^{-2}=\frac{1}{3^2}=\frac{1}{9}$

\end{tcolorbox}

\vspace{-0.4cm}

\end{multicols}

\vspace{-1.2cm}

### Exercise 15.2 {-}

\vspace{-0.6cm}

\begin{enumerate}
    \item State the value each of the following logarithms:
    \begin{enumerate}
        \begin{multicols}{5}
            \item $\log_6{36}$
            \item $\log_5{125}$
            \item $\log_4{16}$
            \item $\log_2{16}$
            \item $\log_9{81}$
        \end{multicols}
        \begin{multicols}{5}
            \item $\log_3{81}$
            \item $\log_2{32}$
            \item $\log_{10}{100}$
            \item $\log_8{64}$
            \item $\log_4{64}$
        \end{multicols}
        \begin{multicols}{5}
            \item $\log_7{7}$
            \item $\log_3{9}$
            \item $\log_8{1}$
            \item $\log_5{25}$
            \item $\log_5{5}$
        \end{multicols}
        \begin{multicols}{5}
            \item $\log_2{32}$
            \item $\log_{4}{4}$
            \item $\log_2{1}$
            \item $\log_6{216}$
            \item $\log_{2}{128}$
        \end{multicols}
    \end{enumerate}
    \item By considering negative and fractional indices, evaluate each:
    \begin{enumerate}
        \begin{multicols}{5}
            \item $\log_9{3}$
            \item $\log_{64}{8}$
            \item $\log_{25}{5}$
            \item $\log_100{10}$
            \item $\log_{8}{2}$
        \end{multicols}
        \begin{multicols}{5}
            \item $\log_{27}{3}$
            \item $\log_4{2}$
            \item $\log_{16}{2}$
            \item $\log_{81}{3}$
            \item $\log_{11}{121}$
        \end{multicols}
        \begin{multicols}{5}
            \item $\log_5{\frac{1}{5}}$
            \item $\log_3{\frac{1}{3}}$
            \item $\log_{6}{\frac{1}{36}}$
            \item $\log_2{\frac{1}{8}}$
            \item $\log_9{\frac{1}{3}}$
        \end{multicols}
    \end{enumerate}
    \item Calculate the value of each to three significant figures: \faCalculator
    \begin{enumerate}
        \begin{multicols}{5}
            \item $\log_2{31}$
            \item $\log_{7}{50}$
            \item $\log_{10}{99}$
            \item $\log_5{120}$
            \item $\log_{2}{0.9}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Laws of Logs

\vspace{-0.5cm}

There are two key identities that can be obtained from the definition of a logarithm. For all $a>0$:

\begin{multicols}{5}

\begin{center}
\begin{tcolorbox}[colback=white,width=3.5cm,colframe=white,height=1cm]

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=3.5cm,colframe=red!70!black,height=1cm]

\begin{center}
$\log_a{1}=0$ 
\end{center}

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=white,width=3.5cm,colframe=white,height=1cm]

\begin{center}
and
\end{center}

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=3.5cm,colframe=red!70!black,height=1cm]

\begin{center}
$\log_a{a}=1$ 
\end{center}

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=white,width=3.5cm,colframe=white,height=1cm]


\end{tcolorbox}
\end{center}

\end{multicols}

\vspace{-0.9cm}

There also three *"log laws"* that can be applied for logarithms of the *same base*. For all $a,x,y>0$:

\vspace{-0.5cm}

\begin{multicols}{3}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=5.8cm,colframe=red!70!black,height=2cm]

The \textbf{product law}:\\[-0.2cm]

$\log_a{(xy)}=\log_a{x}+\log_a{y}$ 

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=5.8cm,colframe=red!70!black,height=2cm]

The \textbf{quotient law}:\\[-0.2cm]

$\log_a{\left(\frac{x}{y}\right)}=\log_a{x}-\log_a{y}$ 

\end{tcolorbox}
\end{center}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=5.8cm,colframe=red!70!black,height=2cm]

The \textbf{power law}:\\[-0.2cm]

$\log_a{\left(x^y\right)}=y\log_a{x}$ 

\end{tcolorbox}
\end{center}

\end{multicols}

\vspace{-0.3cm}

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=9.3cm]

Evaluate $\log_{6}{8}+2\log_{6}{3}-\log_{6}{2}$.

\tcblower

\vspace{-0.5cm}
\begin{align*}
    &\log_{6}{8}+2\log_{6}{3}-\log_{6}{2}&&\color{PineGreen}\longleftarrow\text{Consider order of operations}\\[0.5em]
    =&\log_{6}{8}+\log_{6}{\left(3^2\right)}-\log_{6}{2} && \color{PineGreen}\longleftarrow\text{Apply power law}\\[0.5em]
    =&\log_{6}{8}+\log_{6}{9}-\log_{6}{2} &&\\[0.5em]
    =&\log_{6}{\left(8\times 9\right)}-\log_{6}{2} && \color{PineGreen}\longleftarrow\text{Apply product law}\\[0.5em]
    =&\log_{6}{72}-\log_{6}{2} &&\\[0.3em]
    =&\log_{6}{\left(\frac{72}{2}\right)} && \color{PineGreen}\longleftarrow\text{Apply product law}\\[0.3em]
    =&\log_{6}{36} &&\\[0.5em]
    =&2 && \color{PineGreen}\longleftarrow\text{Evaluate}\\[0.5em]
\end{align*}

\vspace{-0.5cm}

\end{tcolorbox}

\vspace{-0.6cm}

### Exercise 15.3 {-}

\vspace{-0.4cm}

\begin{enumerate}
    \item Evaluate each of the following:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_6{9}+\log_6{4}$
            \item $\log_{12}{2}+\log_{12}{6}$
            \item $\log_{2}{3}+\log_2{\frac{1}{3}}$
        \end{multicols}
        \begin{multicols}{3}
            \item $\log_{3}{54}-\log_{3}{2}$
            \item $\log_{5}{10}-\log_{5}{2}$
            \item $\log_{5}{100}-\log_{5}{4}$
        \end{multicols}
        \begin{multicols}{3}
            \item $2\log_4{6}-\log_{4}{9}$
            \item $\log_{12}{4}+2\log_{12}{6}$
            \item $3\log_6{2}+\log_{6}{9}-\log_{6}{2}$
        \end{multicols}
        \begin{multicols}{3}
            \item $2\log_6{3}+\log_{6}{\frac{2}{3}}$
            \item $\log_5{4}+2\log_{5}{10}$
            \item $2\log_{2}{6}-\log_{2}{12}+\log_2{\frac{1}{6}}$
        \end{multicols}
    \end{enumerate}
    \item Simplify each, giving an answer in the form $\log_p{q}$ where $p$ and $q$ are positive integers:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_7{3}+\log_7{6}-\log_{7}{9}$
            \item $\frac{1}{2}\log_{6}{9}-\log_{6}{2}$
            \item $2\log_{8}{9}-3\log_2{3}$
        \end{multicols}
    \end{enumerate}
    \item Simplify each, giving an answer in the form $\log_a{p}$ where $p$ is a positive integer:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_a{3}+2\log_a{4}$
            \item $\frac{1}{3}\log_{a}{8}-\log_{a}{4}$
            \item $\log_{a}{20}-\log_a{4}+\log_a{\frac{1}{15}}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Solving Log Equations

\vspace{-0.5cm}

To solve a *log equation*, it is typically desirable to have each side within a logarithm of the *same base*:

\vspace{-0.4cm}

\begin{center}
\begin{tcolorbox}[colback=red!5,width=11cm,colframe=red!70!black,height=2.2cm]
\vspace{-0.5cm}

\begin{align*}
    \text{If }\hspace{1.0cm} \log_a{x}&=\log_a{y}\\[0.5em]
    \text{ then }\hspace{1.4cm} x&=y \qquad \qquad (\text{where }a>0,x>0,y>0)
\end{align*}

\end{tcolorbox}
\end{center}

\vspace{-0.5cm}

"Cancelling the logs", mathematically, is raising each side to an exponential base $a$, using $a^{\log_a{b}}=b$.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=5.5cm]

Solve the equation $\log_3{x}+\log_3{5}=\log_3{20}$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
\log_3{x}+\log_3{5}&=\log_3{20} &&\\[0.5em]
\log_3{5x}&=\log_3{20} && \color{PineGreen}\longleftarrow\text{Apply product law}\\[0.5em]
5x&=20 && \color{PineGreen}\longleftarrow\text{``Cancel'' }\log_3\text{ from both sides}\\[0.5em]
x&=4 && \color{PineGreen}\longleftarrow\text{Solve}
\end{align*}

\end{tcolorbox}

To express any term as a logarithm, multiply it by $\log_a{a}$ (which equals 1) and then apply the power law:

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=6cm]

Solve the equation $\log_3{x}-\log_3{2}=2$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
\log_3{x}-\log_3{2}&=2\color{PineGreen}\log_3{3} &&\color{PineGreen}\longleftarrow\text{Multiply the constant by}\log_33\\[0.5em]
\log_3{\left(\frac{x}{2}\right)}&=\log_3{3^2} && \color{PineGreen}\longleftarrow\text{Apply quotient and power laws}\\[0.5em]
\frac{x}{2}&=9 && \color{PineGreen}\longleftarrow\text{``Cancel'' }\log_3\text{ from both sides}\\[0.5em]
x&=18 && \color{PineGreen}\longleftarrow\text{Multiply both sides by }2\text{ to solve}
\end{align*}

\end{tcolorbox}

\vspace{-0.5cm}

### Exercise 15.4 {-}

\vspace{-0.4cm}

\begin{enumerate}
    \item Solve:
    \vspace{-0.2cm}
    \begin{enumerate} 
        \begin{multicols}{2}
            \item $\log_{5}{3}+\log_{5}{x}=\log_{5}{18}$
            \item $\log_{7}{2x}+\log_{7}{4}=\log_{7}{56}$
        \end{multicols}
        \begin{multicols}{2}    
            \item $\log_{6}{5}+\log_{5}{(x-1)}=\log_{6}{30}$
            \item $\log_{a}{x}-2\log_{a}{3}=\log_{a}{18}$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{8}{2x}-\log_{8}{3}=\log_{8}{1}$
            \item $\log_{3}{8}-\log_{3}{x}=\log_{3}{2}$
        \end{multicols}
    \end{enumerate}
    \item Solve each:
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_{6}{x}+\log_{6}{12}=2$
            \item $\log_{4}{x}+\log_{4}{8}=2$
            \item $\log_{2}{10}+\log_{2}{x}=4$
        \end{multicols}
        \begin{multicols}{3}
            \item $\log_{5}{x}-\log_{5}{2}=1$
            \item $\log_{3}{x}-2\log_{3}{2}=2$
            \item $\log_{4}{2}+3\log_{4}{x}=2$
        \end{multicols}
        \begin{multicols}{3}
            \item $\log_{2}{5}+3=\log_{2}{(x+2)}$
            \item $\log_{3}{(2x)}-1=\log_{3}{8}$
            \item $2-\log_{6}{(x-3)}=2\log_{6}{3}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

Some algebraic manipulations used to solve an equation may produce solutions do not, in fact, satisfy the original equation. These **extraneous solutions** can arise when solving log equations.

Since $\log_a{x}$ is only defined for $a>0$ and $x>0$, any solutions which contradict this must be discarded.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=8.6cm]

Solve the equation $\log_3{x}+\log_3{(x-2)}=\log_3{8}$.

\tcblower

\begin{align*}
\log_3{x}+\log_3{(x-2)}&=\log_3{8}&&\color{PineGreen}\longleftarrow\text{Note }x>0\text{ and }(x-2)>0\text{ therefore }x>2\\[0.5em]
\log_3{\left(x(x-2)\right)}&=\log_3{8} && \color{PineGreen}\longleftarrow\text{Apply product law}\\[0.5em]
x^2-2x&=8 && \color{PineGreen}\longleftarrow\text{``Cancel'' }\log_3\text{ and expand}\\[0.5em]
x^2-2x-8&=0 && \color{PineGreen}\longleftarrow\text{Equate quadratic equation to zero}\\[0.5em]
(x+2)(x-4)&=0 && \color{PineGreen}\longleftarrow\text{Factorise}\\[0.5em]
x+2=0,x-4&=0 &&\\[0.5em]
\hcancel[PineGreen]{x=-2},x&=4 && \color{PineGreen}\longleftarrow\text{Discard }x=-2\text{ since }x>2
\end{align*}

\end{tcolorbox}

All solutions for $x$ must be checked carefully to verify that they satisfy the *original* log equation.

\begin{enumerate}[resume]
    \item Solve for $x$:
    \begin{enumerate} 
        \begin{multicols}{2}
            \item $\log_{a}{x}+\log_{a}{(x+1)}=\log_{a}{6}$
            \item $\log_{4}{x}+\log_{4}{(x-3)}=\log_{4}{10}$
        \end{multicols}
        \begin{multicols}{2}    
            \item $\log_{6}{(x-1)}+\log_{6}{x}=1$
            \item $\log_{3}{(x+3)}-\log_{3}{x}=2$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{5}{(x+2)}+\log_{5}{(x-3)}=\log_{5}{6}$
            \item $\log_{a}{3}=\log_{a}{(x+5)}+\log_{a}{2x}$
        \end{multicols}
    \end{enumerate}
    \item Solve each:
    \begin{enumerate}
        \begin{multicols}{2}
            \item $\log_{5}{x^2}+\log_{5}{4}=\log_{5}{36}$
            \item $\log_{6}{2}+\log_{6}{x^2}=\log_{6}{50}$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{a}{7}+\log_{a}{x^2}=\log_{a}{14}$
            \item $2\log_{a}{x}+\log_{a}{3}=\log_{a}{48}$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{9}{4}+2\log_{9}{x}=2\log_{9}{8}$
            \item $2\log_{7}{3x}+\log_{7}{2}=\log_{7}{18}$
        \end{multicols}
    \end{enumerate}
    \item Solve each for $a$:
    \begin{enumerate}
        \begin{multicols}{2}
            \item $\log_{a}{3}+\log_{a}{2}=1$
            \item $\log_{a}{18}-\log_{a}{2}=1$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{a}{4}+\log_{a}{2}=3$
            \item $\log_{a}{12}-\log_{a}{4}=\frac{1}{2}$
        \end{multicols}
        \begin{multicols}{2}
            \item $\log_{a}{16}+\log_{a}{4}=2$
            \item $\log_{a}{50}-\log_{a}{2}=2$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Graphs of Logarithmic Functions

\vspace{-0.5cm}

Given a function $f$, defined on a suitable domain such that an inverse function exists, the graph of its inverse function $y=f^{-1}(x)$ can be obtained by \textcolor{PineGreen}{\textbf{reflecting}} the graph of $y=f(x)$ in the line $y=x$.

Since the inverse to the exponential function $f(x)=a^x$ is the \textcolor{PineGreen}{\textbf{logarithmic function}} $f^{-1}(x)=\color{PineGreen}\log_a{x}$, knowledge of exponential graphs allows log graphs to be sketched:

\vspace{-0.6cm}

\begin{center}
    \begin{tikzpicture}[scale=0.8]
        \draw[-stealth] (-4,0) -- (5,0) node[below] {$x$};
        \draw[-stealth] (0,-4) -- (0,4) node[left] {$y$};
        \draw[dashed,thin] (-2.5,-2.5) -- (3.5,3.5) node[above right] {$y=x$};
        \draw[smooth,thick,domain=-4:3] plot (\x,{1.5^(\x)}) node[above left] {$y=a^x$};
        \draw[PineGreen,smooth,thick,domain=0.2:3.36] plot (\x,{(ln(\x))/ln(1.5)}) node[below right] {$y=\log_ax$};
        \draw[fill] (0,1) circle (0.07) node[above left] {$1$};
        \draw[PineGreen,fill] (1,0) circle (0.07) node[below right] {$1$};
        \draw[fill] (1,1.5) circle (0.07) node[above,xshift=-0.5em] {$(1,a)$};
        \draw[PineGreen,fill] (1.5,1) circle (0.07) node[right] {$(a,1)$};
        \node[below] at (12,4.5) {
        \begin{minipage}{7.5cm}
        The graph of $y=a^x$ passes through...
        \vspace{0.3cm}
        \begin{center}
        $(0,1)$ and $(1,a)$
        \end{center}
        \vspace{0.2cm}
        ...and has a \textbf{horizontal} asymptote of $x=0$.\\[0.1em]
        \end{minipage}
        };
        \node[below] at (12,1) {
        \begin{minipage}{7.5cm}
        The graph of \textcolor{PineGreen}{$y=\log_ax$} passes through...
        \begin{center}
        \textcolor{PineGreen}{$(1,0)$} and \textcolor{PineGreen}{$(a,1)$}.
        \end{center}
        \vspace{-0.1cm}
        ..and has a \textcolor{PineGreen}{\textbf{vertical}} asymptote of \textcolor{PineGreen}{$y=0$}.
        \end{minipage}
        };
        \node[below] at (12,-2.5) {
        \begin{minipage}{7.5cm}
        In general, if $y=f(x)$ passes through $(x,y)$ then $y=f^{-1}(x)$ passes through $(y,x)$.
        \end{minipage}
        };
    \end{tikzpicture}
\end{center}

\vspace{-0.5cm}

Knowledge of the graph of $y=\log_a{x}$ may be combined with and understanding of graph transformations.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=6.7cm]

Sketch the graph of $y=\log_3{(x-1)}+2$.

\vspace{-0.2cm}

\tcblower

\textcolor{PineGreen}{Consider $y=\log_3{(x-1)}+2$ as a $f(x-1)+3$ transformation of $y=\log_3{x}$:}

\vspace{-0.4cm}

\begin{center}
    \begin{tikzpicture}[scale=0.6]
        \draw[-stealth,xshift=-12cm] (-0.5,0) -- (5,0) node[below] {$x$};
        \draw[-stealth,xshift=-12cm] (0,-2.2) -- (0,4) node[left] {$y$};
        \draw[smooth,thin,domain=0.1:3.5,PineGreen,xshift=-12cm] plot (\x,{(ln(\x))/(ln(3))}) node[right] {$y=\log_3{x}$};
        \draw[PineGreen,fill,xshift=-12cm] (1,0) circle (0.05) node[below] {$1$};
        \draw[PineGreen,fill,xshift=-12cm] (3,1) circle (0.05) node[above] {$(3,1)$};
        \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
        \draw[-stealth] (0,-2.2) -- (0,4) node[left] {$y$};
        \draw[smooth,thick,domain=0.04:3.5,xshift=1cm,yshift=2cm] plot (\x,{(ln(\x))/(ln(3))}) node[right] {$y=\log_3{(x-1)}+2$};
        \draw[black,fill] (2,2) circle (0.05) node[below right] {$(2,2)$};
        \draw[black,fill] (4,3) circle (0.05) node[above] {$(4,3)$};
        \draw[dashed] (1,-2) -- (1,3.5) node[above] {\scriptsize{$x=1$}};
        \draw[PineGreen,-stealth] (-4.5,1) -- (-1.5,1);
        \node[above,PineGreen] at (-3,1) {\textit{``Right 1''}};
        \node[below,PineGreen] at (-3,1) {\textit{``Up 2''}};
    \end{tikzpicture}
\end{center}

\end{tcolorbox}

\vspace{-0.5cm}

### Exercise 15.5 {-}

\vspace{-0.5cm}

\begin{enumerate}
    \item Sketch each of the following:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $y=\log_{5}{x}$
        \item $y=\log_{2}{x}$
        \item $y=\log_{9}{x}$
    \end{multicols}
    \end{enumerate}
    \item Sketch each of the following, showing clearly where any asymptote is not along an axis:
    \begin{enumerate}
    \begin{multicols}{3}
        \item $y=\log_{4}{x}+1$
        \item $y=\log_{7}{x}-2$
        \item $y=\log_{5}{x}+3$
    \end{multicols}
    \begin{multicols}{3}
        \item $y=\log_{8}{(x+5)}$
        \item $y=\log_{2}{(x-3)}$
        \item $y=\log_{6}{(x+2)}$
    \end{multicols}
    \begin{multicols}{3}
        \item $y=\log_{7}{(x+3)}+2$
        \item $y=\log_{5}{(x-3)}-1$
        \item $y=\log_{6}{(x+2)}+1$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

As in section 15.1 (Graphs of Exponential Functions), substitution of known coordinates on the graph of a log function  into its equation can allow unknown constants it contains to be determined.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

The graph of $y=\log_a{(x+b)}$ is below. Find the values of $a$ and $b$.

\begin{center}
    \begin{tikzpicture}[scale=0.9]
        \draw[-stealth] (-4,0) -- (5,0) node[below] {$x$};
        \draw[-stealth] (0,-1.5) -- (0,1.5) node[left] {$y$};
        \draw[smooth,thick,domain=0.1:7,xshift=-3cm] plot (\x,{ln(\x)/ln(5)}) node[right] {$y=\log_a{(x+b)}$};
        \draw[fill] (-2,0) circle (0.05) node[below] {$-2$};
        \draw[fill] (2,1) circle (0.05) node[below] {$(2,1)$};
        \draw[dashed] (-3,-1.5) -- (-3,1.1) node[above] {$x=-3$};
    \end{tikzpicture}
\end{center}

\vspace{-0.3cm}

\tcblower

\vspace{-0.6cm}
\begin{align*}
    0&=\log_a{(-2+b)} && \color{PineGreen}\longleftarrow\text{Substitute }(-2,0)\\[0.5em]
    -2+b&=1 &&\color{PineGreen}\longleftarrow\text{Since }\log_a{1}=0\text{ for all }a\\[0.5em]
    b&=3 && \color{PineGreen}\longleftarrow\text{Solve to obtain }b\\[1em]
    1&=\log_a{(2+3)} && \color{PineGreen}\longleftarrow\text{Substitute }(2,1)\text{ and }b=3\\[0.5em]
    a&=5 &&\color{PineGreen}\longleftarrow\text{Since }\log_a{a}=1\text{ for all }a\\[1em]
    y&=\log_5{(x+3)}&&\color{PineGreen}\longleftarrow\text{State equation}
\end{align*}

\end{tcolorbox}

\begin{enumerate}[resume]
    \item Determine the equation of each, using the form given:
    \begin{enumerate}
        \begin{multicols}{2}
            \item $y=\log_4{(x+a)}$\\
                \begin{tikzpicture}
                    \draw[white] (-2,-2) rectangle (5.5,3);
                    \draw[-stealth] (-2,0) -- (5,0) node [above] {$x$};
                    \draw[-stealth] (0,-2) -- (0,3) node[left] {$y$};
                    \draw[smooth,thick,domain=0.1:6,xshift=-2cm,yshift=0cm] plot (\x,{ln(\x)/ln(4)});
                    \draw[fill] (-1,0) circle (0.05) node[below] {$-1$};
                    \draw[fill] (2,1) circle (0.05) node[above] {$(2,1)$};
                    \draw[dashed] (-2,-2) -- (-2,3);
                \end{tikzpicture}
            \item $y=\log_a{(x-2)}$\\
                \begin{tikzpicture}
                    \draw[white] (-2,-2) rectangle (5.5,3);
                    \draw[-stealth] (-2,0) -- (5,0) node [above] {$x$};
                    \draw[-stealth] (-2,-2) -- (-2,3) node[left] {$y$};
                    \draw[smooth,thick,domain=0.1:4,xshift=0cm,yshift=0cm] plot (\x,{ln(\x)/ln(3)});
                    \draw[fill] (1,0) circle (0.05) node[below] {$3$};
                    \draw[fill] (3,1) circle (0.05) node[above] {$(5,1)$};
                    \draw[dashed] (0,-2) -- (0,3);
                \end{tikzpicture}
        \end{multicols}
        \begin{multicols}{2}
            \item $y=\log_a{(x+b)}$\\
                \begin{tikzpicture}
                    \draw[white] (-0.5,-2) rectangle (5.5,3);
                    \draw[-stealth] (-0.5,0) -- (6,0) node [above] {$x$};
                    \draw[-stealth] (0,-2) -- (0,3) node[left] {$y$};
                    \draw[smooth,thick,domain=0.1:5.5,xshift=1cm,yshift=0cm] plot (\x,{ln(\x)/ln(5)});
                    \draw[fill] (2,0) circle (0.05) node[below] {$2$};
                    \draw[fill] (6,1) circle (0.05) node[above] {$(6,1)$};
                    \draw[dashed] (1,-2) -- (1,3);
                \end{tikzpicture}
            \item $y=\log_a{(bx)}$\\
                \begin{tikzpicture}
                    \draw[white] (-2,-2) rectangle (5.5,3);
                    \draw[-stealth] (-2,0) -- (5,0) node [above] {$x$};
                    \draw[-stealth] (0,-2) -- (0,3) node[left] {$y$};
                    \draw[smooth,thick,domain=0.1:9,xshift=0cm,yshift=0cm,xscale=0.5] plot (\x,{ln(\x)/ln(6)});
                    \draw[fill] (0.5,0) circle (0.05) node[below right] {$0.5$};
                    \draw[fill] (3,1) circle (0.05) node[above] {$(3,1)$};
                \end{tikzpicture}
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Solving Exponential Equations

\vspace{-0.5cm}

To solve an \textcolor{PineGreen}{\textit{exponential equation}} such as $10=2^{\color{PineGreen}x}$, which has a non-integer solution, the relationship between a log and an exponential of the same base, stated in section 15.2, can be used as follows:

\vspace{-0.3cm}

\begin{align*}
    \text{If }\hspace{1.9cm} 10&=2^{\color{PineGreen}x}\\[0.5em]
    \text{ then }\hspace{0.5cm} \color{PineGreen}\log_2{\color{black}10}&=x
\end{align*}

\vspace{-0.3cm}

The solution, using a calculator and correct to three significant figures, is $x=3.32$. This makes use of the property $\color{PineGreen}\log_a{a^{\color{black}x}}\color{black}=x$, which follows from the inverse relationship between a log and exponential.

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

Solve the equation $14=3\times5^x$, giving the answer correct to three significant figures. \faCalculator

\tcblower

\vspace{-0.5cm}

\begin{align*}
14&=3\times 5^x &&\\[0.5em]
\frac{14}{3}&=5^x && \color{PineGreen}\longleftarrow\text{Divide both sides by 3}\\[0.5em]
\log_5{\left(\frac{14}{3}\right)}&=x && \color{PineGreen}\longleftarrow\text{Take }\log_5\text{ of both sides}\\[0.5em]
x&=0.957 \text{ (to 3sf)} && \color{PineGreen}\longleftarrow\text{Calculate the solution}
\end{align*}

\end{tcolorbox}

\vspace{-0.3cm}

### Exercise 15.6 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Solve, giving the answers to three significant figures: \faCalculator
    \begin{enumerate}
        \begin{multicols}{4}
            \item $30=5^x$
            \item $6=3^x$
            \item $13=8^x$
            \item $3=7^x$
        \end{multicols}
        \begin{multicols}{4}
            \item $2^x=11$
            \item $10^x=500$
            \item $6^x=3$
            \item $4^x=65$
        \end{multicols}
        \begin{multicols}{4}
            \item $19=2.1^t$
            \item $1.3^{2y}=0.7$
            \item $7^{4p}=\frac{1}{2}$
            \item $\frac{2}{3}=4^{0.7k}$
        \end{multicols}
    \end{enumerate}
    \item Solve, giving the answers to three significant figures: \faCalculator
    \begin{enumerate}
        \begin{multicols}{4}
            \item $12=4\times8^x$
            \item $24=6\times7^x$
            \item $2=7\times5^x$
            \item $21=4\times3^x$
        \end{multicols}
        \begin{multicols}{4}
            \item $6\times8^x=5$
            \item $3\times4^x=45$
            \item $0.03\times8^x=0.7$
            \item $18\times5^x=0.7$
        \end{multicols}
        \begin{multicols}{4}
            \item $5=3\times4^q$
            \item $7\times6^{0.03t}=5$
            \item $10\times10^{-3y}=9$
            \item $10=9\times10^{-0.037k}$
        \end{multicols}
    \end{enumerate}
    \item Solve, giving the answer to three significant figures: \faCalculator
    \begin{enumerate}
        \begin{multicols}{3}
            \item $20=4\times7^x+3$
            \item $7=\frac{1}{2}\times3^x-6$
            \item $5+3\times4^x=23$
        \end{multicols}
        \begin{multicols}{3}
            \item $3\times\left(\frac{1}{2}\right)^x=7$
            \item $6\times1.4^x-2.3=31.4$
            \item $0.4=3\times0.3^x-0.5$
        \end{multicols}
        \begin{multicols}{3}
            \item $3\times4^{0.0723k}=21$
            \item $11\times3^{-0.104x}=6$
            \item $3=5\times2^{-0.00562k}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Natural Logarithms

\vspace{-0.5cm}

Some logarithms with particular *bases* are routinely used in various fields, such as the *binary logarithm* $\left(\log_2\right)$ in computer science, or the the *decimal* or *common logarithm* $\left(\log_{10}\text{ or just }\log\right)$ in engineering.

The most useful logarithm in mathematics is the \textcolor{PineGreen}{\textbf{natural logarithm}} ($\log_{\color{PineGreen}e}$ or more often just \textcolor{PineGreen}{$\ln$}), which takes Euler's Number \textcolor{PineGreen}{$e$} as its base, where \textcolor{PineGreen}{$e\approx 2.719$}. (Its lies in the ease which which exponentials in base $e$ can be used together with calculus, which is beyond the scope of this course.)

The *laws of logs* apply to natural logarithms since they apply to *all* $\log_a$ where $a>0$:

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=6.7cm]

Simplify $\ln{48}-3\ln{2}$, giving the answer in the form $\ln{p}$.

\tcblower

\vspace{-0.5cm}

\begin{align*}
&\ln{48}-2\ln{2} &&\\[0.5em]
=&\ln{48}-\ln{\left(2^3\right)} && \color{PineGreen}\longleftarrow\text{Apply the power law}\\[0.5em]
=&\ln{48}-\ln{8} &&\\[0.5em]
=&\ln{\left(\frac{48}{8}\right)}&& \color{PineGreen}\longleftarrow\text{Apply the quotient law}\\[0.5em]
=&\ln{6} && \color{PineGreen}\longleftarrow\text{Simplify}
\end{align*}

\vspace{-0.2cm}

\end{tcolorbox}

Exponential equations in base $\color{PineGreen}e$ are solved using the natural logarithm $\color{PineGreen}\ln$, since $\color{PineGreen}\ln{\left(e^{\color{black}x}\right)}=x$:

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen,height=7.6cm]

Given $37=21e^{-0.48x}$, find the value of $k$ to three significant figures. \faCalculator

\tcblower

\vspace{-0.5cm}

\begin{align*}
37&=21e^{-0.48k} &&\\[0.5em]
\frac{37}{21}&=e^{-0.48k} && \color{PineGreen}\longleftarrow\text{Divide both sides by 21}\\[0.5em]
\ln{\left(\frac{37}{21}\right)}&=-0.48k && \color{PineGreen}\longleftarrow\text{Take }\ln\text{ of both sides}\\[0.5em]
\frac{\ln{\left(\frac{37}{21}\right)}}{-0.48}&=k && \color{PineGreen}\longleftarrow\text{Divide both sides by }-0.48\\[0.5em]
k&=1.18 \text{ (to 3sf)} && \color{PineGreen}\longleftarrow\text{Calculate the solution}
\end{align*}

\vspace{-0.2cm}

\end{tcolorbox}

\vspace{-0.5cm}

### Exercise 15.7 {-}

\vspace{-0.5cm}

\begin{enumerate}
    \item Fo each, find the value of $k$ to three significant figures: \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{4}
            \item $0.7=e^{k}$
            \item $1.8=e^{k}$
            \item $3e^{k}=24$
            \item $4=7e^{x}$
        \end{multicols}
        \begin{multicols}{4}
            \item $125=5e^{2k}$
            \item $50=7e^{4k}$
            \item $10=12e^{-3k}$
            \item $17=100^{-5k}$
        \end{multicols}
    \end{enumerate}
    \item Solve each for $x$, giving the answers to three significant figures: \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{4}
            \item $120=85e^{0.475x}$
            \item $50=32e^{0.0273x}$
            \item $14=23e^{-0.381x}$
            \item $3P=Pe^{0.045x}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\vspace{-0.2cm}

\pagebreak

## Exponential Growth and Decay

\vspace{-0.5cm}

The behaviour of many real-world things are described by \textcolor{PineGreen}{\textbf{exponential growth}} or \textcolor{PineGreen}{\textbf{exponential decay}}.

Time, $t$, is a common variable for such a function in place of $x$, and it typically describes the behaviour of some real-world variable which is named suitably in place of $y$ of $f(x)$, such as $V$ for *"value"*, $P$ for *"population size"* or $M$ for *"mass"*. Where $\color{PineGreen}k>0$:

\setlength{\columnsep}{30pt}

\begin{multicols}{2}

\vspace{-0.2cm}

$V=V_0e^{\color{PineGreen}k\color{black}t}$ describes the \textcolor{PineGreen}{\textbf{exponential growth}} of $V$ from some initial value $V_0$ as $t$ increases.

\vspace{-0.5cm}
\begin{center}
    \begin{tikzpicture}[scale=0.7]
        \draw[-stealth] (0,0) -- (8,0) node[below] {$t$};
        \draw[-stealth] (0,0) -- (0,6) node[left] {$V$};
        \node[below left] {O};
        \draw[smooth,thick,PineGreen,domain=0:5] plot (\x,{0.5*1.6^(\x)}) node[right] {$\color{black}V=V_0e^{\color{PineGreen}k\color{black}t}$};
        \draw[fill] (0,0.5) circle (0.05) node[left] {$V_0$};
    \end{tikzpicture}
\end{center}

\columnbreak

\vspace{-0.2cm}

$V=V_0e^{\color{PineGreen}-k\color{black}t}$ describes the \textcolor{PineGreen}{\textbf{exponential decay}} of $V$ from some initial value $V_0$ as $t$ increases.

\vspace{-0.5cm}
\begin{center}
    \begin{tikzpicture}[scale=0.7]
        \draw[-stealth] (0,0) -- (8,0) node[below] {$t$};
        \draw[-stealth] (0,0) -- (0,6) node[left] {$V$};
        \node[below left] {O};
        \draw[smooth,thick,PineGreen,domain=0:5] plot (\x,{4*0.7^(\x)}) node[right] {$\color{black}V=V_0e^{\color{PineGreen}-k\color{black}t}$};
        \draw[fill] (0,4) circle (0.05) node[left] {$V_0$};
    \end{tikzpicture}
\end{center}

\end{multicols}

\vspace{-0.5cm}

\setlength{\columnsep}{10pt}

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

80 micrograms of a radioactive substance, which decays over time, is obtained. The mass $M$ micrograms of the substance remaining after $t$ hours can be modelled by the equation:

\vspace{-0.3cm}

\[M=M_0e^{-kt}\]

\vspace{-0.1cm}

\begin{enumerate}
    \item[(a)] State the value of $M_0$.
\end{enumerate}

\tcblower

\vspace{-0.5cm}

\begin{align*}
M_0&=80 && \color{PineGreen}\longleftarrow M_0\text{ is the initial value}
\end{align*}

\end{tcolorbox}

Constant $k$ may be found through substitution if initial value $V_0$ is known and the value of $V$ at time $t$.

\begin{tcolorbox}[colback=PineGreen!2!, colframe=PineGreen]

\begin{enumerate}
    \item[(b)] After 5 hours, only 50.7 micrograms of the substance remains.\newline Determine the value of $k$, rounded to three significant figures. \faCalculator
\end{enumerate}

\tcblower

\vspace{-0.5cm}

\begin{align*}
50.7&=80e^{-k\times 5} && \color{PineGreen}\longleftarrow \text{Substitute }M_0=80\text{, }M=50.7\text{ and }t=5\\[0.5em]
\frac{50.7}{80}&=e^{-5k} && \color{PineGreen}\longleftarrow \text{Divide by }80\\[0.5em]
\ln{\left(\frac{50.7}{80}\right)}&=-5k && \color{PineGreen}\longleftarrow \text{Take natural log of both sides }\\[0.5em]
\frac{\ln{\left(\frac{50.7}{80}\right)}}{-5}&=k && \color{PineGreen}\longleftarrow \text{Divide both sides by }(-5)\\[0.5em]
k&=0.0912 && \color{PineGreen}\longleftarrow \text{Calculate and round as required}
\end{align*}

\end{tcolorbox}

A feature of exponential functions is that the time taken for the value to grow or decay by any given proportion is always constant. For example the time taken for an exponential growth function to double a value from 20 to 40 will be the same time it will take to double from 50 to 100.

\pagebreak

\begin{tcolorbox}[colback=PineGreen!2!, colframe=PineGreen]

\begin{enumerate}
    \item[(c)] Find the time it will take for only half of the original substance to remain (its \textit{half-life}). \faCalculator
\end{enumerate}

\tcblower

\vspace{-0.5cm}

\begin{align*}
40&=80e^{-0.0912t} && \color{PineGreen}\longleftarrow \text{Substitute }M=40\text{ and }k=0.0912\text{ is now known}\\[0.5em]
\frac1{2}&=e^{-0.0912t} && \color{PineGreen}\longleftarrow \text{Divide by }80\text{ and simplify}\\[0.5em]
\ln{\left(\frac{1}{2}\right)}&=-0.0912t && \color{PineGreen}\longleftarrow \text{Take natural log of both sides }\\[0.5em]
\frac{\ln{\left(\frac{1}{2}\right)}}{-0.0912}&=t && \color{PineGreen}\longleftarrow \text{Divide both sides by }(-5)\\[0.5em]
t&=7.60\text{ hours} && \color{PineGreen}\longleftarrow \text{Calculate}
\end{align*}

\end{tcolorbox}

\vspace{-0.5cm}

### Exercise 15.8 {-}

\vspace{-0.3cm}

All questions: \faCalculator

\vspace{-0.2cm}

\begin{enumerate}
    \item For each \textit{exponential growth} function, find the value of $t$ it will take for the value to double:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $V=40e^{0.3t}$
            \item $P(t)=25e^{0.08t}$
            \item $M=M_0e^{0.00572t}$
        \end{multicols}
    \end{enumerate}
    \item The number of bacteria in a population, $B$, can be modelled using the equation $B=400e^{0.0376t}$ where $t$ is time measured in minutes.
    \begin{enumerate}
        \item State the number of bacteria in the population initially.
        \item Find, to the nearest thousand, the number of bacteria after 45 minutes.
        \item Determine the time it takes for the population of bacteria to double in size.
    \end{enumerate}
    \item A population of deer is growing exponentially in an area, and the size of the population, $P$, can be described by the equation $P=860e^{0.173t}$, where $t$ is the number of years from 2026.
    \begin{enumerate}
        \item State the number of deer in the population in 2026.
        \item Find, to the nearest ten, the number of deer expected to be in the population in 2028.
        \item Determine the time it will take for the population of deer to double in size.
    \end{enumerate}
    \item For each \textit{exponential decay} function, find the value of $t$ it will take for the value to halve:
    \begin{enumerate}
        \begin{multicols}{3}
            \item $T=20e^{-0.8t}$
            \item $V(t)=360e^{-0.072t}$
            \item $P=P_0e^{-0.00197t}$
        \end{multicols}
    \end{enumerate}
    \item The temperature $T$ (in $\degree\text{C}$) of a substance $t$ minutes after the end of an experiment can be modelled by the equation $T=T_0e^{-kt}$. After 7 minutes, the substance has cooled from $140\degree\text{C}$ to $55\degree\text{C}$.
    \begin{enumerate}
        \item Determine the value of $k$ to three significant figures.
        \item Find the time taken for the substance to cool to $30\degree\text{C}$.
    \end{enumerate}
    \item The concentration $C$ of a drug in a patient's blood $t$ hours after being given a dose can be modelled by the equation $C=28e^{-kt}$.
    \begin{enumerate}
        \item If the concentration is 23 after 90 minutes, calculate the value of $k$ to three significant figures.
        \item Find the time taken for the concentrate to reduce by half.
        \item Find the time taken for the concentration to be only 15\% of its original value.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Experimental Data of the form $y=ax^b$

\vspace{-0.5cm}

Where a relationship between variables $x$ and $y$ is a \textcolor{PineGreen}{power} function in the form
$\color{PineGreen}y=a\color{PineGreen}x^{\color{PineGreen}b}$, taking any $\log$ of both sides will reveal the \textcolor{PineGreen}{linear relationship} that therefore exists between $\color{PineGreen}\log{x}$ and $\color{PineGreen}\log{y}$.

\vspace{-0.4cm}

\begin{minipage}{0.33\textwidth}
\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$\color{PineGreen}x$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\color{PineGreen}y$};
          \node[below left] {\scriptsize{O}};
          \draw[PineGreen,thick,smooth,domain=0:2.6] plot (\x,{0.5*(\x)^2}) node[above] {$y\color{black}=a\color{PineGreen}x^{\color{black}b}$};
\end{tikzpicture}
\end{center}
\end{minipage}\begin{minipage}{0.33\textwidth}
\begin{align*}
    \color{PineGreen}y&=a\color{PineGreen}x^{\color{black}b}\\[0.3em]
    \log{y}&=\log{\left(ax^b\right)}\\[0.5em]
    \log{y}&=\log{x^b}+\log{a}\\[0.5em]
    \color{PineGreen}\log{y}&=b\color{PineGreen}\log{x}\color{black}+\log{a}\\
    &\hspace{0.45cm} \downarrow\hspace{1.6cm}\downarrow\\
    \color{PineGreen}\log{y}&=m\color{PineGreen}\log{x}\color{black}+c
\end{align*}
\end{minipage}\begin{minipage}{0.33\textwidth}
\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$\color{PineGreen}\log{x}$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\color{PineGreen}\log{y}$};
          \node[below left] {\scriptsize{O}};
          \draw[PineGreen,thick,smooth,domain=0:3] plot (\x,{0.8*(\x)+1});
          \draw[fill] (0,1) circle (0.05) node[left] {$\log{a}$};
          \node[rotate=38.66] at (1.8,2) {gradient $=b$};
\end{tikzpicture}
\end{center}
\end{minipage}

Drawing such a plot of $\color{PineGreen}\log{y}$ against $\color{PineGreen}\log{x}$ and obtaining a straight line can be used to check for a power relationship. Where a relationship is of the form $y=ax^b$, determining the values of $a$ and $b$ is possible by first finding the *gradient* and $y$*-intercept* on the $\color{PineGreen}\log{y}\sim\log{x}$ graph. 

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

Two variables, $x$ and $y$, are connected by the equation $y=kx^n$. The graph of $\log_3{y}$ against $\log_3{x}$ is a straight line as shown. Determine the values of $k$ and $n$.

\vspace{-0.3cm}

\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$\log_3{x}$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\log_3{y}$};
          \node[below left] {\scriptsize{O}};
          \draw[thick] plot (0,1) -- (3,2.5);
          \draw[fill] (0,1) circle (0.05) node[left] {$(0,3)$};
          \draw[fill] (2,2) circle (0.05) node[below right] {$(2,6)$};
\end{tikzpicture}
\end{center}

\vspace{-0.6cm}

\tcblower

\vspace{-0.5cm}

\begin{align*}
\log_{3}y&=\log_3{\left(kx^n\right)} && \color{PineGreen}\longleftarrow \text{Take }\log_3\text{ of both sides}\\[0.5em]
\log_{3}y&=\log_3{x^n}+\log_3{k} && \color{PineGreen}\longleftarrow \text{Apply product law}\\[0.5em]
\log_{3}y&=n\log_3{x}+\log_3{k} && \color{PineGreen}\longleftarrow \text{Apply power law}\\[1em]
\text{gradient}&=\frac{6-3}{2-0}=\frac{3}{2} && \color{PineGreen}\longleftarrow \text{Find gradient}\\[0.5em]
n&=\frac{3}{2} && \color{PineGreen}\longleftarrow \text{Equate to }n\\[1em]
y\text{-intercept}&=3 && \color{PineGreen}\longleftarrow \text{Find }y\text{-intercept}\\[0.5em]
\log_{3}k&=3 && \color{PineGreen}\longleftarrow \text{Equate to }\log_3{k}\\[0.5em]
\log_{3}k&=3\color{PineGreen}\log_3{3} && \color{PineGreen}\longleftarrow \text{Solve for }k\\[0.5em]
\log_{3}k&=\log_3{3^3} &&\\[0.5em]
k&=27 &&
\end{align*}

\end{tcolorbox}

Therefore the relationship between $x$ and $y$ is $y=27x^{\frac{3}{2}}$.

\pagebreak


\newpage

### Exercise 15.9 {-}

\begin{enumerate}
    \item For each graph where the relationship between $x$ and $y$ is $y=kx^n$, determine the values of $k$ and $n$:
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(a)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(b)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(c)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(d)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \item For each graph where the relationship between $x$ and $y$ is $y=ax^b$, determine the values of $a$ and $b$:
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(a)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(b)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(c)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(d)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$\log_a{x}$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
\end{enumerate}

\newpage

## Experimental Data of the form $y=ab^x$

\vspace{-0.5cm}

Where a relationship between variables $x$ and $y$ is an \textcolor{PineGreen}{exponential} function in the form
$\color{PineGreen}y=ab^{\color{PineGreen}x}$, taking any $\log$ of both sides will reveal the \textcolor{PineGreen}{linear relationship} that therefore exists between $\color{PineGreen}x$ and $\color{PineGreen}\log y$.

\vspace{-0.3cm}

\begin{minipage}{0.33\textwidth}
\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$\color{PineGreen}x$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\color{PineGreen}y$};
          \node[below left] {\scriptsize{O}};
          \draw[PineGreen,thick,smooth,domain=0:3.1] plot (\x,{0.5*1.8^(\x)}) node[above] {$y\color{black}=ab^{\color{PineGreen}x}$};
\end{tikzpicture}
\end{center}
\end{minipage}\begin{minipage}{0.33\textwidth}
\begin{align*}
    \color{PineGreen}y&=ab^{\color{PineGreen}x}\\[0.5em]
    \log{y}&=\log{\left(ab^x\right)}\\[0.5em]
    \log{y}&=\log{b^x}+\log{a}\\[0.5em]
    \color{PineGreen}\log{y}&=\color{PineGreen}x\color{black}\log{b}\color{black}+\log{a}\\
    &\hspace{0.75cm} \downarrow\hspace{1.1cm}\downarrow\\
    \color{PineGreen}\log{y}&=\color{PineGreen}x\color{black}m\hspace{0.3cm}+\hspace{0.2cm}c
\end{align*}
\end{minipage}\begin{minipage}{0.33\textwidth}
\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$x$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\color{PineGreen}\log{y}$};
          \node[below left] {\scriptsize{O}};
          \draw[PineGreen,thick,smooth,domain=0:3] plot (\x,{0.8*(\x)+1});
          \draw[fill] (0,1) circle (0.05) node[left] {$\log{a}$};
          \node[rotate=38.66] at (1.8,2) {gradient $=\log{b}$};
\end{tikzpicture}
\end{center}
\end{minipage}

Drawing such a plot of $\color{PineGreen}\log{y}$ against $\color{PineGreen}x$ and obtaining a straight line can be used to check for an exponential relationship. Where a relationship is of the form $y=ab^x$, determining the values of $a$ and $b$ is possible by first finding the *gradient* and $y$*-intercept* on the $\color{PineGreen}\log{y}\sim x$ graph. 

\begin{tcolorbox}[title=Example,colback=PineGreen!2!, colframe=PineGreen]

Two variables, $x$ and $y$, are connected by the equation $y=ab^x$. The graph of $\log_9{y}$ against $x$ is a straight line as shown. Determine the values of $a$ and $b$.

\vspace{-0.3cm}

\begin{center}
\begin{tikzpicture}[scale=0.8]
          \draw[-stealth] (-0.2,0) -- (4,0) node[below] {$x$};
          \draw[-stealth] (0,-0.2) -- (0,4) node[left] {$\log_9{y}$};
          \node[below left] {\scriptsize{O}};
          \draw[thick] plot (0,1) -- (3,2.5);
          \draw[fill] (0,1) circle (0.05) node[left] {$(0,2)$};
          \draw[fill] (2,2) circle (0.05) node[below right] {$(4,4)$};
\end{tikzpicture}
\end{center}

\vspace{-0.6cm}

\tcblower

\vspace{-0.5cm}

\begin{align*}
\log_{9}y&=\log_9{\left(ab^x\right)} && \color{PineGreen}\longleftarrow \text{Take }\log_9\text{ of both sides}\\[0.5em]
\log_{9}y&=\log_9{b^x}+\log_9{a} && \color{PineGreen}\longleftarrow \text{Apply product law}\\[0.5em]
\log_{9}y&=x\log_9{b}+\log_9{a} && \color{PineGreen}\longleftarrow \text{Apply power law}\\[1em]
\text{gradient}&=\frac{4-2}{4-0}=\frac{2}{4}=\frac{1}{2} && \color{PineGreen}\longleftarrow \text{Find gradient}\\[0.5em]
\log_9{b}&=\frac{1}{2} && \color{PineGreen}\longleftarrow \text{Equate to }\log_9{b}\\[0.5em]
b&=3 && \color{PineGreen}\longleftarrow \text{Solve for }b\\[1em]
y\text{-intercept}&=2 && \color{PineGreen}\longleftarrow \text{Find }y\text{-intercept}\\[0.5em]
\log_{9}a&=2 && \color{PineGreen}\longleftarrow \text{Equate to }\log_9{a}\\[0.5em]
a&=81 && \color{PineGreen}\longleftarrow \text{Solve for }a
\end{align*}

\end{tcolorbox}

Therefore the relationship between $x$ and $y$ is $y=81\times3^x$.

Note the the process of solving for $a$ and solving for $b$ may require solving each log equation step-by-step.

\pagebreak


\newpage

### Exercise 15.10 {-}

\begin{enumerate}
    \item For each graph where the relationship between $x$ and $y$ is $y=ab^x$, determine the values of $a$ and $b$:
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(a)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(b)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(c)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(d)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \item For each graph where the relationship between $x$ and $y$ is $y=ka^x$, determine the values of $a$ and $k$:
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(a)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(b)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
    \begin{multicols}{2}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(c)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
        \begin{center}
            \begin{tikzpicture}
                \draw[white] (-3,-1) rectangle (6,4);
                \node[below right] at (-3,4) {(d)};
                \draw[-stealth] (-2,0) -- (5,0) node[below] {$x$};
                \draw[-stealth] (0,-1) -- (0,3.5) node[left] {$\log_a{y}$};
                \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
        \end{center}
    \end{multicols}
\end{enumerate}

\newpage

## Logs and Exponentials Review Exercise {-}

