\chapterfont{\color{white}}

# Further Calculus

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[RoyalBlue,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[RoyalBlue,very thick] (5,1) -- (6,1);
\draw[RoyalBlue,fill=RoyalBlue,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Further Calculus}}};
\node at (3,1) {\Large{\textsc{Chapter 16}}};
\end{tikzpicture}
\end{center}

So far in the course, differentiation has required expressions to be written as the sums or differences of powers. For example, differentiating $f(x)=(2x-5)^3$ first requires the expansion of brackets:

\begin{align*}
    f(x)&=(2x-5)^3\\[0.5em]
    &=(2x-5)(2x-5)(2x-5)\\[0.5em]
    &=(2x-5)(4x^2-10x-10x+25)\\[0.5em]
    &=(2x-5)(4x^2-20x+25)\\[0.5em]
    &=8x^3-40x^2+50x-20x^2+100x-125\\[0.5em]
    &=8x^3-60x^2+150x-125\\[1em]
    f'(x)&=24x^2-120x+150
\end{align*}

To begin comparing $f(x)=\color{RoyalBlue}(2x-5)^3$ to its derivative, notice that $f'(x)=2x^2-120x+150$ can be factorised and rearranged as follows:

\begin{align*}
    f'(x)&=24x^2-120x+150\\[0.5em]
    &=6(4x^2-20x+25)\\[0.5em]
    &=6(2x-5)^3\\[0.5em]
    &=\color{RoyalBlue}3(2x-5)^3\color{black}\times2
\end{align*}

Combining this result with knowledge that the derivative of $\color{RoyalBlue}x^3$ is $\color{RoyalBlue}3x^2$ clearly suggests that some method may exist which allows faster derivatives of expressions of the form $\color{RoyalBlue}(ax+b)^n$. Investigation may be used to obtain the following derivatives:

\[\frac{\text{d}}{\text{d}y}\left(\color{RoyalBlue}(7x+2)^4\color{black}\right)=\color{RoyalBlue}4(7x+2)^3\color{black}\times7\]

\[\frac{\text{d}}{\text{d}y}\left(\color{RoyalBlue}(6x-5)^3\color{black}\right)=\color{RoyalBlue}3(6x-5)^2\color{black}\times6\]

At this point the rule differentiating expressions of the form $\color{RoyalBlue}(ax+b)^n$ may possibly be deduced, and this rule is provided on the next page.

In this chapter methods for differentiating and integrating a number of different forms of algebra are introduced (though deriving and proving these rules is beyond the scope of the course).

\pagebreak

## Differentiating $(ax+b)^n$

\vspace{-0.5cm}

\textcolor{RoyalBlue}{Powers of }$\color{RoyalBlue}{(ax+b)}$ may be differentiated using the rule below, as seen on the previous page.

\begin{center}
\begin{tcolorbox}[colback=red!5,width=13.5cm,colframe=red!70!black,height=2.2cm]
\vspace{-0.5cm}

\begin{align*}
    \text{If }\hspace{1.4cm} f(x)&=(ax+b)^n\\[0.5em]
    \text{ then }\hspace{0.8cm} f'(x)&=n(ax+b)^{n-1}\times a \qquad (\text{where }a,b,n\text{ are constants})
\end{align*}

\end{tcolorbox}
\end{center}

This may be summarised as:

\begin{itemize}
    \item Keep the bracket the same.
    \item Multiply by the power, then reduce the power by one.
    \item Multiply by the $x$-coefficient.
\end{itemize}

\begin{multicols}{2}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!2!, colframe=RoyalBlue,width=8.5cm,height=4.1cm]

Given $y=(2x+3)^5$, find $\frac{\text{d}y}{\text{d}x}$.

\vspace{-0.1cm}
\tcblower

\vspace{-0.4cm}

\begin{align*}
\frac{\text{d}y}{\text{d}x}&=5(2x+3)^4\times2\\[0.5em]
&=20(2x+3)^4
\end{align*}

\end{tcolorbox}



\begin{tcolorbox}[title=Example,colback=RoyalBlue!2!, colframe=RoyalBlue,width=8.5cm,height=4.1cm]

Given $f(x)=4(3-x)^6$, find $f'(x)$.

\vspace{-0.1cm}
\tcblower

\vspace{-0.3cm}

\begin{align*}
f'(x)&=6\times4(3-x)^5\times(-1)\\[0.5em]
&=-24(3-x)^5
\end{align*}

\end{tcolorbox}

\end{multicols}

\vspace{-1cm}

[]{#ex161q}

#### [Exercise 16.1](#ex161a) {-}

\vspace{-0.5cm}

\newpage

## The Chain Rule for Differentiation

\vspace{-0.5cm}

The rule introduced on the previous page is part of a more general rule for differentiating expressions of the form $\color{RoyalBlue}{f\left(g(x)\right)}$, called the \textcolor{RoyalBlue}{Chain Rule for Differentiation}.

\begin{center}
\begin{tcolorbox}[colback=red!5,width=12cm,colframe=red!70!black,height=2.2cm]
\vspace{-0.5cm}

\begin{align*}
    \text{If }\hspace{1.4cm} h(x)&=f(\left(g(x)\right)\\[0.5em]
    \text{ then }\hspace{0.8cm} h'(x)&=f'\left(g(x)\right)\times g'(x)
\end{align*}

\end{tcolorbox}
\end{center}

This may be summarised as:

\begin{itemize}
    \item Keep the \textcolor{RoyalBlue}{inner function} in the bracket the same.
    \item Differentiate the \textcolor{RoyalBlue}{outer function}.
    \item Multiply by the \textcolor{RoyalBlue}{derivative of the outer function}.
\end{itemize}

\begin{multicols}{2}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!2!, colframe=RoyalBlue,width=8.5cm,height=5.6cm]

Given $y=(2x^3-1)^8$, find $\dfrac{\text{d}y}{\text{d}x}$.

\vspace{-0.1cm}
\tcblower

\vspace{-0.1cm}

\begin{align*}
\frac{\text{d}y}{\text{d}x}&=8(2x^3-1)^7\times 6x^2\\[1em]
&=48x^2(2x^3-1)^7
\end{align*}

\end{tcolorbox}


\begin{tcolorbox}[title=Example,colback=RoyalBlue!2!, colframe=RoyalBlue,width=8.5cm,height=5.6cm]

Given $f(x)=\sqrt[3]{x^2+5x+7}^{\;4}$, find $f'(x)$.

\vspace{-0.1cm}
\tcblower

\vspace{-0.3cm}

\begin{align*}
f(x)&=(x^2+5x+7)^{\frac{4}{3}}\\[0.5em]
f'(x)&=\frac{4}{3}(x^2+5x+7)^{\frac{1}{3}}\times(2x+5)\\[0.5em]
&=\frac{4}{3}(2x+5)\sqrt[3]{x^2+5x+7}
\end{align*}

\end{tcolorbox}

\end{multicols}

\vspace{-1cm}

[]{#ex162q}

#### [Exercise 16.2](#ex162a) {-}

\vspace{-0.5cm}

\newpage

## Differentiating Trig Functions

\vspace{-0.5cm}

The trigonometric expressions $\sin{x}$ and $\cos{x}$ can be differentiated quickly, if $x$ is measured in \textcolor{RoyalBlue}{radians}. 

\begin{figure}[H]
    \centering
    \begin{minipage}{7cm}
        \begin{tcolorbox}[colback=red!5,colframe=red!70!black,height=2.2cm,width=6.2cm]
            \vspace{-0.5cm}
            \begin{center}
                \begin{align*}
                    \text{If }\hspace{1.4cm} f(x)&=\sin{x}\\[0.5em]
                    \text{ then }\hspace{0.8cm} f'(x)&=\cos{x}
                \end{align*}
            \end{center}
        \end{tcolorbox}
    \end{minipage}%
    \begin{minipage}{1cm}
    \end{minipage}%
    \begin{minipage}{7cm}
        \begin{tcolorbox}[colback=red!5,colframe=red!70!black,height=2.2cm,width=6.2cm]
            \vspace{-0.5cm}
            \begin{center}
                \begin{align*}
                    \text{If }\hspace{1.4cm} f(x)&=\sin{x}\\[0.5em]
                    \text{ then }\hspace{0.8cm} f'(x)&=\cos{x}
                \end{align*}
            \end{center}
        \end{tcolorbox}
    \end{minipage}
\end{figure}

\vspace{-0.5cm}

A versions of these rules may be found on the Higher formula sheet, stating the derivatives of $\sin{ax}$ and $\cos{ax}$. However they may be more powerfully combined with the Chain Rule for Differentiation, allowing expressions such as $\color{RoyalBlue}{\sin{(3x-\pi)}}$ to be differentiated, giving $\color{RoyalBlue}{\cos{(3x-\pi)}}\color{black}\times 3=3\cos{(3x-\pi)}$.



\newpage

### Exercise {-}

\newpage

## Integrating Trig Functions

\newpage

### Exercise {-}

\newpage

### Exercise {-}

\newpage

## Integrating $(ax+b)^n$

\newpage

### Exercise {-}

\newpage

## Review Exercise {-}
