\chapterfont{\color{white}}

# Answers {-}

\vspace{-10.5cm}

\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[white,rounded corners,very thick] (1,0.2) rectangle (5,1.8);
\draw[black!60,fill=black!60,rounded corners] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Answers}}};
\end{tikzpicture}
\end{center}

### Chapter 1 Answers {-}

\newpage



\newpage

### Chapter 2 Answers {-}

\newpage



\newpage

### Chapter 3 Answers {-}

\newpage



\newpage

### Chapter 4 Answers {-}

\newpage



\newpage

### Chapter 5 Answers {-}

\newpage



\newpage

### Chapter 6 Answers {-}

\newpage



\newpage

### Chapter 7 Answers {-}

\newpage



\newpage

### Chapter 8 Answers {-}

\newpage



\newpage

### Chapter 9 Answers {-}

\newpage



\newpage

### Chapter 10 Answers {-}

\newpage



\newpage

### Chapter 11 Answers {-}

\newpage



\newpage

### Chapter 12 Answers {-}

\newpage



\newpage

### Chapter 13 Answers {-}

\newpage



\newpage

### Chapter 14 Answers {-}

\vspace{-0.2cm}

\begingroup
\footnotesize

\vspace{-0.2cm}

[]{#ex141a}

#### [Exercise 14.1](#ex141q) {-}

\vspace{-0.2cm}

\begin{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $13\cos{(x-67.4)\degree}$
        \item $\sqrt{41}\cos{(x-38.7)\degree}$
        \item $\sqrt{37}\cos{(x-9.5)\degree}$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $10\cos{(x-126.9)\degree}$
        \item $\sqrt{10}\cos{(x-288.4)\degree}$
        \item $\sqrt{5}\cos{(x-243.4)\degree}$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{2}\cos{(x-45)\degree}$
        \item $2\cos{(x-300)\degree}$
        \item $2\cos{(x-210)\degree}$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

\vspace{-0.3cm}

[]{#ex142a}

#### [Exercise 14.2](#ex142q) {-}

\vspace{-0.2cm}

\begin{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{13}\sin{(x+56.3)\degree}$
        \item $5\sin{(x+36.9)\degree}$
        \item $5\sqrt{2}\sin{(x+98.1)\degree}$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{73}\cos{(x+5.92)}$
        \item $5\cos{(x+2.21)}$
        \item $2\sqrt{10}\cos{(x+1.25)}$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $2\sin{\left(x-\frac{5\pi}{6}\right)}$
        \item $\sqrt{2}\sin{\left(x-\frac{5\pi}{4}\right)}$
        \item $4\sin{\left(x-\frac{\pi}{6}\right)}$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

\vspace{-0.3cm}

[]{#ex143a}

#### [Exercise 14.3](#ex143q) {-}

\vspace{-0.2cm}

\begin{enumerate}
    \item Sketches showing turning points and roots:
    \begin{multicols}{2}
            \begin{tikzpicture}
            \draw[white] (-0.5,-2) rectangle (6.6,2);
            \draw[-stealth] (0,0) -- (6.4,0) node[above] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,1.6) node[left] {$y$};
            \draw[thick,smooth,xshift=0.61cm,domain=-0.61:5.673] plot (\x,{cos(\x r)});
            \node[below] at (2*3.141592,0) {$360$};
            \node[below] at (3.141592,0) {$180$};
            \draw[fill] (0.61,1) circle (0.05) node[above right] {$(35\degree,7)$};
            \draw[fill] (3.141592+0.61,-1) circle (0.05) node[below] {$(215\degree,-7)$};
            \draw[fill] (0.5*3.141592+0.61,0) circle (0.05) node[above right] {$125\degree$};
            \draw[fill] (1.5*3.141592+0.61,0) circle (0.05) node[above left] {$305\degree$};
            \node[left] at (0,1) {$7$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-7$};
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
            \end{tikzpicture}
        \columnbreak  
        \vfill
        a) $y=7\cos{(x-35)}\degree$:
        \begin{itemize}
            \item maximum turning point at $(35\degree,7)$
            \item minimum turning point at $(215\degree,-7)$
            \item $x$-intercepts at $(125\degree,0)$ and $(305\degree,0)$
        \end{itemize}
        \end{multicols}
        \begin{multicols}{2}
            \begin{tikzpicture}
            \draw[white] (-0.5,-2) rectangle (6.6,2);
            \draw[-stealth] (0,0) -- (6.4,0) node[above] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,1.6) node[left] {$y$};
            \draw[thick,smooth,xshift=0.4cm,domain=-0.4:5.883] plot (\x,{sin(\x r)});
            \draw[fill] (0.5*3.141592+0.4,1) circle (0.05) node[above] {$(113\degree,3)$};
            \draw[fill] (1.5*3.141592+0.4,-1) circle (0.05) node[below] {$(293\degree,-3)$};
            \draw[fill] (3.141592+0.4,0) circle (0.05) node[above right] {$203\degree$};
            \draw[fill] (0*3.141592+0.4,0) circle (0.05) node[below right] {$23\degree$};
            \node[below] at (2*3.141592,0) {$360$};
            \node[below] at (3.141592,0) {$180$};
            \node[left] at (0,1) {$3$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-3$};
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
            \end{tikzpicture}
        \columnbreak    
        \vfill
        b) $y=3\sin{(x-23)}\degree$:
        \begin{itemize}
            \item maximum turning point at $(113\degree,3)$
            \item minimum turning point at $(293\degree,-3)$
            \item $x$-intercepts at $(23\degree,0)$ and $(203\degree,0)$
        \end{itemize}
        \end{multicols}
        \begin{multicols}{2}
            \begin{tikzpicture}
            \draw[white] (-0.5,-2) rectangle (6.6,2);
            \draw[-stealth] (0,0) -- (6.4,0) node[above] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,1.6) node[left] {$y$};
            \draw[thick,smooth,xshift=-0.716cm,domain=0.716:6.999] plot (\x,{cos(\x r)});
            \draw[fill] (2*3.141592-0.716,1) circle (0.05) node[above] {$(319\degree,\sqrt{5})$};
            \draw[fill] (1*3.141592-0.716,-1) circle (0.05) node[below] {$(139\degree,-\sqrt{5})$};
            \draw[fill] (0.5*3.141592-0.716,0) circle (0.05) node[above right] {$49\degree$};
            \draw[fill] (1.5*3.141592-0.716,0) circle (0.05) node[above left] {$229\degree$};
            \node[below] at (2*3.141592,0) {$360$};
            \node[below] at (3.141592,0) {$180$};
            \node[left] at (0,1) {$7$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-7$};
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
            \end{tikzpicture}
        \columnbreak
        \vfill
        c) $y=\sqrt{5}\cos{(x+41)}\degree$:
        \begin{itemize}
            \item maximum turning point at $(319\degree,\sqrt{5})$
            \item minimum turning point at $(139\degree,-\sqrt{5})$
            \item $x$-intercepts at $(49\degree,0)$ and $(229\degree,0)$
        \end{itemize}
    \end{multicols}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item max value $8$ when $x\degree=140\degree$
        \item max value $\sqrt{2}$ when $x\degree=333\degree$
        \item max value $7$ when $x\degree=47.7\degree$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item min value $-3$ when $x=\frac{7\pi}{6}$
        \item min value $-3$ when $x=\frac{7\pi}{6}$
        \item min value $-12$ when $x=\frac{\pi}{4}$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{85}\sin{(x-49.4)\degree}$
        \item max TP at $(139.4\degree,2\sqrt{85})$, min TP at $(219.4\degree,-2\sqrt{85})$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

\endgroup

\pagebreak

\begingroup
\footnotesize

[]{#ex144a}

#### [Exercise 14.4](#ex144q) {-}

\begin{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $x\degree=52.8\degree,163.2\degree$
        \item $x\degree=97.8\degree,194.2\degree$
        \item $x\degree=79.4\degree,312.6\degree$
    \end{multicols}
    \end{enumerate}
    \item $x\degree=83.1\degree,203.1\degree$
    \item 
    \begin{enumerate}
    \begin{multicols}{3}
        \item $2\cos{(x-60)\degree}$
        \item $x\degree=180\degree,300\degree$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $x=3.08,5.72$
        \item $x=4.06,6.02$
        \item $x=1.52,3.26$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{13}\sin{(x+0.98)}$
        \item $x=1.73,5.73$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex145a}

#### [Exercise 14.5](#ex145q) {-}

\begin{enumerate}
    \item $5\sin{(t-233.1)\degree}$
    \item $\sqrt{5}\cos{(2x-2.04)}$
    \item 
    \begin{enumerate}
    \begin{multicols}{3}
        \item $13\sin{(t+67.4)\degree}$ 
        \item max value of $13$ occurs when $t=22.6$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $2\cos{\left(2x-\frac{5\pi}{6}\right)}$
        \item $x=\frac{\pi}{4},\frac{7\pi}{12},\frac{5\pi}{4},\frac{19\pi}{12}$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex14Ra}

#### [Review Exercise](#ex14Rq) {-}

\begin{enumerate}
    \item $\sqrt{113}\sin{(x+41.2)\degree}$
    \item $\sqrt{6}\cos{(x-1.15)}$
    \item $2\sin{\left(x+\frac{2\pi}{3}\right)}$
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{34}\cos{(x+59.0)\degree}$
        \item P$(74.3\degree,-4)$ and Q$(167.7\degree,-4)$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $2\sqrt{5}\sin{(x-63.4)\degree}$
        \item 
        \begin{enumerate}
            \item max value is $2\sqrt{5}$
            \item occurs when $x=153.4$
        \end{enumerate}
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \item $2\cos{\left(x-\frac{\pi}{3}\right)}$
        \item Sketch of $y=\cos{x}+\sqrt{3}\sin{x}$:
        \begin{center}
        \begin{tikzpicture}
            \draw[white] (-0.5,-2) rectangle (6.6,2);
            \draw[-stealth] (0,0) -- (6.4,0) node[above] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,1.6) node[left] {$y$};
            \draw[thick,smooth,xshift=1.047cm,domain=-1.047:5.236] plot (\x,{cos(\x r)});
            \node[below] at (2*3.141592,0) {$360$};
            \node[below] at (3.141592,0) {$180$};
            \draw[fill] (1.047,1) circle (0.05) node[above] {$\left(\frac{\pi}{3},2\right)$};
            \draw[fill] (3.141592+1.047,-1) circle (0.05) node[below] {$\left(\frac{4\pi}{3},-2\right)$};
            \draw[fill] (0.5*3.141592+1.047,0) circle (0.05) node[above right] {$\frac{5\pi}{6}$};
            \draw[fill] (1.5*3.141592+1.047,0) circle (0.05) node[above left] {$\frac{11\pi}{6}$};
            \node[left] at (0,1) {$2$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-2$};
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
            \end{tikzpicture}
            \end{center}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $3\sqrt{5}\cos{(x+26.6)\degree}$
        \item $x=90,216.9$
    \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
    \begin{multicols}{3}
        \item $\sqrt{2}\sin{(2x-45)\degree}$
        \item $x=22.5,112.5,202.5,292.5$
    \end{multicols}
    \end{enumerate}
\end{enumerate}

\endgroup

\pagebreak

### Chapter 15 Answers {-}

\vspace{-0.2cm}

\begingroup
\footnotesize

\vspace{-0.2cm}

[]{#ex151a}

#### [Exercise 15.1](#ex151q) {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $y=3^x$\newline$k=9$
            \item $y=\left(\frac{1}{2}\right)^x$\newline$k=1$
            \item $y=2^x$\newline$k=8$
            \item $y=4^x-5$\newline$k=-5$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{4}
            \item $y=2^x+2$\newline$k=2$
            \item $y=2^x+3$\newline$k=7$
            \item $y=4^x-1$\newline$k=1$
            \item $y=3^x-2$\newline$k=-\frac{5}{3}$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{2}
            \item $y=3^x$, range $f(x)>0$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2:2] plot (\x,{0.4*3^(\x)});
            \draw[fill] (0,0.4) circle (0.07) node[above left] {$1$};
            \draw[fill] (1,1.2) circle (0.07) node[right,xshift=0.1cm] {$(1,3)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \end{center}
            \item $y=3^x+1$, range $f(x)>1$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2:1.8,yshift=0.4cm] plot (\x,{0.4*3^(\x)});
            \draw[fill] (0,0.8) circle (0.07) node[above left] {$2$};
            \draw[fill] (1,1.6) circle (0.07) node[right,xshift=0.1cm] {$(1,4)$};
            \node[below left] {\scriptsize{O}};
            \draw[dashed] (-2.5,0.4) -- (2,0.4) node[right] {$y=1$};
            \end{tikzpicture}
            \end{center}
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{2}
            \item $y=3^x-2$, range $f(x)>-2$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2:2.1,yshift=-0.8cm] plot (\x,{0.4*3^(\x)});
            \draw[fill] (0,-0.4) circle (0.07) node[right] {$-1$};
            \draw[fill] (1,0.4) circle (0.07) node[right,xshift=0.1cm] {$(1,1)$};
            \node[below left] {\scriptsize{O}};
            \draw[dashed] (-2.5,-0.8) -- (2,-0.8) node[right] {$y=-2$};
            \end{tikzpicture}
            \end{center}
            \item $y=3^{x+2}$, range $f(x)>0$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.2) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-2:2,xshift=-2cm] plot (\x,{0.4*3^(\x)});
            \draw[fill] (-2,0.4) circle (0.07) node[above left] {$(-2,2)$};
            \draw[fill] (-1,1.2) circle (0.07) node[above left] {$(-1,4)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \end{center}
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{2}
            \item $y=\left(\frac{1}{2}\right)^x$, range $f(x)>0$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.8) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-3.5:3.5] plot (\x,{0.75^(\x)});
            \draw[fill] (0,1) circle (0.07) node[below left] {$1$};
            \draw[fill] (2.40942,0.5) circle (0.07) node[above right] {$\left(1,\frac{1}{2}\right)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \end{center}
            \item $y=\left(\frac{1}{2}\right)^x-1$, range $f(x)>-1$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1.8) -- (0,4) node[left] {$y$};
            \draw[smooth,thick,domain=-3.5:3.5,yshift=-1cm] plot (\x,{0.75^(\x)});
            \draw[fill] (0,0) circle (0.07);
            \draw[fill] (2.40942,-0.5) circle (0.07) node[above,yshift=0.4cm] {$\left(1,-\frac{1}{2}\right)$};
            \node[below left] {\scriptsize{O}};
            \draw[dashed] (-2.5,-1) -- (2,-1) node[right] {$y=-1$};
            \end{tikzpicture}
            \end{center}
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{2}
            \item $y=\left(\frac{1}{2}\right)^{x-2}$, range $f(x)>0$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (1,-1) -- (1,3) node[left] {$y$};
            \draw[smooth,thick,domain=-2.5:4.5,xshift=-1cm] plot (\x,{0.75^(\x)});
            \draw[fill] (-1,1) circle (0.07) node[below left] {$(-2,1)$};
            \draw[fill] (0.2,0.7) circle (0.07) node[above] {$\left(-1,\frac{1}{2}\right)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \end{center}
            \item $y=\left(\frac{1}{2}\right)^{1-x}$, range $f(x)>0$\\
            \begin{center}
            \begin{tikzpicture}[scale=0.7]
            \draw[-stealth] (-4,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (0,-1) -- (0,3) node[left] {$y$};
            \draw[smooth,thick,domain=-5:1.2,xshift=2.409cm] plot (\x,{0.75^(-\x)});
            \draw[fill] (2.409,1) circle (0.07) node[below] {$(1,1)$};
            \draw[fill] (0,0.5) circle (0.07) node[above left] {$\left(0,\frac{1}{2}\right)$};
            \node[below left] {\scriptsize{O}};
            \end{tikzpicture}
            \end{center}
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\endgroup

\pagebreak

\begingroup
\footnotesize

[]{#ex152a}

#### [Exercise 15.2](#ex152q) {-}

\begin{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{5}
            \item $2$
            \item $3$
            \item $2$
            \item $4$
            \item $2$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{5}
            \item $4$
            \item $5$
            \item $2$
            \item $2$
            \item $3$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{5}
            \item $1$
            \item $2$
            \item $0$
            \item $2$
            \item $1$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{5}
            \item $6$
            \item $1$
            \item $0$
            \item $3$
            \item $7$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{5}
            \item $\frac{1}{2}$
            \item $\frac{1}{2}$
            \item $\frac{1}{2}$
            \item $\frac{1}{2}$
            \item $\frac{1}{3}$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{5}
            \item $\frac{1}{3}$
            \item $\frac{1}{2}$
            \item $\frac{1}{4}$
            \item $\frac{1}{4}$
            \item $2$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{5}
            \item $-1$
            \item $-1$
            \item $-2$
            \item $-3$
            \item $-\frac{1}{2}$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{5}
            \item $4.95$
            \item $2.01$
            \item $1.99$
            \item $2.97$
            \item $-0.152$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex153a}

#### [Exercise 15.3](#ex153q) {-}

\begin{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{3}
            \item $2$
            \item $1$
            \item $0$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{3}
            \item $3$
            \item $1$
            \item $2$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{3}
            \item $1$
            \item $2$
            \item $2$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{3}
            \item $1$
            \item $2$
            \item $-1$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_7{2}$
            \item $\log_{6}{15}$
            \item $\log_2{3}$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\log_a{48}$
            \item $\log_{a}{6}$
            \item $\log_{a}{2}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex154a}

#### [Exercise 15.4](#ex154q) {-}


\begin{enumerate}
    \item Solve:
    \vspace{-0.2cm}
    \begin{enumerate} 
        \begin{multicols}{6}
            \item $x=6$
            \item $x=7$
            \item $x=7$
            \item $x=54$
            \item $x=\frac{3}{2}$
            \item $x=4$
        \end{multicols}
    \end{enumerate}
    \item Solve each:
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{6}
            \item $x=3$
            \item $x=2$
            \item $x=1.6$
            \item $x=10$
            \item $x=36$
            \end{multicols}
            \end{enumerate}
            \begin{enumerate}[resume]
            \begin{multicols}{6}
            \item $x=2$
            \item $x=38$
            \item $x=12$
            \item $x=7$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate} 
        \begin{multicols}{6}
            \item $x=2$
            \item $x=5$
            \item $x=3$
            \item $x=2$
            \item $x=4$
            \item $x=\frac{1}{2}$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{6}
            \item $x=3$
            \item $x=5$
            \item $x=\sqrt{2}$
            \item $x=4$
            \item $x=4$
            \item $x=1$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{6}
            \item $a=6$
            \item $a=9$
            \item $a=2$
            \item $a=9$
            \item $a=8$
            \item $a=5$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\endgroup

\pagebreak

\begingroup
\footnotesize

\vspace{-0.5cm}

[]{#ex155a}

#### [Exercise 15.5](#ex155q) {-}

\vspace{-0.5cm}

\begin{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{3}
            \item $y=\log_{5}x$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.1:8,xscale=0.8] plot (\x,{(ln(\x))/(ln(5))});
            \draw[black,fill] (0.8,0) circle (0.05) node[below right] {$1$};
            \draw[black,fill] (0.8*5,1) circle (0.05) node[above] {$(5,1)$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{2}x$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.22:3,xscale=2] plot (\x,{(ln(\x))/(ln(2))});
            \draw[black,fill] (2,0) circle (0.05) node[below right] {$1$};
            \draw[black,fill] (2*2,1) circle (0.05) node[above] {$(2,1)$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{9}x$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.05:15,xscale=0.5] plot (\x,{(ln(\x))/(ln(9))});
            \draw[black,fill] (0.5,0) circle (0.05) node[below right] {$1$};
            \draw[black,fill] (0.5*9,1) circle (0.05) node[above] {$(9,1)$};
            \end{tikzpicture}
        \end{center}
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{3}
            \item $y=\log_{4}x+1$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.05:8,xscale=0.8,yscale=0.7,yshift=0.7cm] plot (\x,{(ln(\x))/(ln(4))});
            \draw[black,fill] (0.8,0.49) circle (0.05) node[above] {$(1,1)$};
            \draw[black,fill] (0.8*4,1.19) circle (0.05) node[above] {$(4,2)$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{7}x-1$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.05:12,xscale=0.6,yscale=0.5,yshift=-1cm] plot (\x,{(ln(\x))/(ln(7))});
            \draw[black,fill] (0.6,-0.5) circle (0.05) node[below right] {$(1,-1)$};
            \draw[black,fill] (4.2,0) circle (0.05) node[above] {$(7,0)$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{5}x+2$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.05:7,xscale=1,yscale=0.5,yshift=1.5cm] plot (\x,{(ln(\x))/(ln(5))});
            \draw[black,fill] (1,0.75) circle (0.05) node[above] {$(1,2)$};
            \draw[black,fill] (5,1.25) circle (0.05) node[above] {$(5,3)$};
            \end{tikzpicture}
        \end{center}
        \end{multicols}
    \end{enumerate}
    \begin{enumerate}[resume]
        \begin{multicols}{3}
            \item $y=\log_{8}(x-5)$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=5.01:15,xscale=0.5] plot (\x,{(ln(\x-5))/(ln(8))});
            \draw[black,fill] (3,0) circle (0.05) node[below right] {$5$};
            \draw[black,fill] (6.5,1) circle (0.05) node[above] {$(8,6)$};
            \draw[dashed] (2.4,-2) -- (2.4,1.5) node[above] {$x=5$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{2}(x+3)$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-4.5,0) -- (4,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=0.22:4,xshift=-3cm] plot (\x,{(ln(\x))/(ln(2))});
            \draw[black,fill] (-2,0) circle (0.05) node[below right] {$-2$};
            \draw[black,fill] (-1,1) circle (0.05) node[above left,xshift=0.2cm,yshift=-0.1cm] {$(-1,1)$};
            \draw[dashed] (-3.1,-2) -- (-3.1,1.5) node[above] {$x=-3$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{3}(x-2)$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-2.2) -- (-0.1,2) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=2.1:11,xscale=0.5] plot (\x,{(ln(\x-2))/(ln(3))});
            \draw[black,fill] (1.5,0) circle (0.05) node[below right] {$3$};
            \draw[black,fill] (2.5,1) circle (0.05) node[below right,yshift=0.2cm,xshift=-0.1cm] {$(5,1)$};
            \draw[dashed] (0.5*1.9,-2) -- (0.5*1.9,1.5) node[above] {$x=2$};
            \end{tikzpicture}
        \end{center}
        \end{multicols}
    \end{enumerate}
    \begin{enumerate}[resume]
        \begin{multicols}{3}
            \item $y=\log_{7}(x+3)+2$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-3.5,0) -- (5,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-0.8) -- (-0.1,3.4) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=-2.89:8,xscale=0.5] plot (\x,{(ln(\x+3))/(ln(7))+2});
            \draw[black,fill] (-1,2) circle (0.05) node[above left] {$(-2,2)$};
            \draw[black,fill] (2,3) circle (0.05) node[below] {$(4,3)$};
            \draw[dashed] (-1.6,3.5) -- (-1.6,0) node[below] {$x=-3$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{5}(x-3)+1$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-0.5,0) -- (8,0) node[below] {$x$};
            \draw[-stealth] (-0.1,-1.2) -- (-0.1,3) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=3.1:12,xscale=0.5] plot (\x,{(ln(\x-3))/(ln(5))+1});
            \draw[black,fill] (2,1) circle (0.05) node[below right] {$(4,1)$};
            \draw[black,fill] (4,2) circle (0.05) node[above] {$(8,2)$};
            \draw[dashed] (1.4,-1) -- (1.4,2.5) node[above] {$x=3$};
            \end{tikzpicture}
        \end{center}
        \item $y=\log_{6}(x+2)-1$\\
            \begin{center}
            \vspace{-0.5cm}
            \begin{tikzpicture}[scale=0.6]
            \draw[-stealth] (-3.5,0) -- (5,0) node[below] {$x$};
            \draw[-stealth] (0,-2.5) -- (0,1.7) node[left] {$y$};
            \draw[smooth,samples=100,thick,domain=-1.9:8,xscale=0.5] plot (\x,{(ln(\x+2))/(ln(6))-1});
            \draw[black,fill] (-0.5,-1) circle (0.05) node[right,xshift=0.2cm] {$(-1,-1)$};
            \draw[black,fill] (2,0) circle (0.05) node[above] {$(4,0)$};
            \draw[dashed] (-1.1,-2.5) -- (-1.1,0.5) node[above,xshift=-0.1cm] {$x=-2$};
            \end{tikzpicture}
        \end{center}
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $y=\log_4{(x+2)}$
            \item $y=\log_3{(x-2)}$
            \item $y=\log_5{(x-1)}$
            \item $y=\log_6{2x}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\vspace{-0.5cm}

[]{#ex156a}

#### [Exercise 15.6](#ex156q) {-}

\vspace{-0.5cm}

\begin{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{6}
            \item $x=2.11$
            \item $x=1.63$
            \item $x=1.23$
            \item $x=0.565$
            \item $x=3.46$
            \item $x=2.70$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{6}
            \item $x=0.613$
            \item $x=3.01$
            \item $t=3.97$
            \item $y=-0.680$
            \item $p=-0.0891$
            \item $k=-0.418$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{6}
            \item $x=0.528$
            \item $x=0.712$
            \item $x=-0.778$
            \item $x=1.51$
            \item $x=-0.0877$
            \item $x=1.95$
            \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{6}
            \item $x=1.51$
            \item $x=-2.02$
            \item $q=0.368$
            \item $t=-6.26$
            \item $y=0.0153$
            \item $k=-1.24$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{6}
            \item $x=0.744$
            \item $x=2.97$
            \item $x=1.29$
            \item $x=-1.22$
            \item $x=5.13$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{6}
            \item $x=1$
            \item $k=19.4$
            \item $x=5.31$
            \item $k=131.1$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\endgroup

\pagebreak

\begingroup
\footnotesize

[]{#ex157a}

#### [Exercise 15.7](#ex157q) {-}

\begin{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{4}
            \item $k=-0.357$
            \item $k=0.588$
            \item $k=2.08$
            \item $k=-0.560$
        \end{multicols}
        \end{enumerate}
        \begin{enumerate}[resume]
        \begin{multicols}{4}
            \item $k=1.61$
            \item $k=0.492$
            \item $k=0.0608$
            \item $k=0.354$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \begin{multicols}{4}
            \item $x=0.726$
            \item $x=16.3$
            \item $x=1.30$
            \item $x=24.4$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex158a}

#### [Exercise 15.8](#ex158q) {-}

\begin{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $t=2.31$
            \item $t=866$
            \item $t=121$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $400$
            \item $2200$
            \item $18.4$ mins
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $860$
            \item $1220$
            \item $4.01$ years
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $t=0.866$
            \item $t=9.63$
            \item $t=352$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $k=0.133$
            \item $11.6$ mins
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{3}
            \item $k=0.131$
            \item $5.29$ hours
            \item $14.5$ hours
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex159a}

#### [Exercise 15.9](#ex159q) {-}

\begin{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $k=49$,$n=5$
            \item $k=16$,$n=\frac{1}{2}$
            \item $k=125$,$n=-\frac{2}{3}$
            \item $k=64$,$n=-\frac{1}{2}$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $a=\frac{1}{3}$,$b=\frac{1}{2}$
            \item $a=\frac{1}{25}$,$b=1$
            \item $a=3$,$b=-2$
            \item $a=\frac{1}{2}$,$b=\frac{1}{18}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex1510a}

#### [Exercise 15.10](#ex1510q) {-}

\begin{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $a=25$,$b=125$
            \item $a=2$,$b=16$
            \item $a=8$,$b=\frac{1}{2}$
            \item $a=\frac{1}{3}$,$b=9$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \begin{multicols}{4}
            \item $k=1000$,$a=\frac{1}{10}$
            \item $k=2$,$a=8$
            \item $k=81$,$a=\frac{1}{9}$
            \item $k=8$,$a=\frac{1}{4}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

[]{#ex15Ra}

#### [Review Exercise](#ex15Rq) {-}



\endgroup

\newpage



\newpage

### Chapter 16 Answers {-}

\newpage



\newpage
